// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.dhcp.message.gpb.message;

/**
 * Protobuf type {@code tr451_vomci_nbi_message.v1.ActionResp}
 */
public final class ActionResp extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:tr451_vomci_nbi_message.v1.ActionResp)
        ActionRespOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use ActionResp.newBuilder() to construct.
    private ActionResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private ActionResp() {
        outputData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
        return new ActionResp();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private ActionResp(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        Status.Builder subBuilder = null;
                        if (statusResp_ != null) {
                            subBuilder = statusResp_.toBuilder();
                        }
                        statusResp_ = input.readMessage(Status.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(statusResp_);
                            statusResp_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 18: {

                        outputData_ = input.readBytes();
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_ActionResp_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_ActionResp_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        ActionResp.class, Builder.class);
    }

    public static final int STATUS_RESP_FIELD_NUMBER = 1;
    private Status statusResp_;

    /**
     * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
     *
     * @return Whether the statusResp field is set.
     */
    @Override
    public boolean hasStatusResp() {
        return statusResp_ != null;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
     *
     * @return The statusResp.
     */
    @Override
    public Status getStatusResp() {
        return statusResp_ == null ? Status.getDefaultInstance() : statusResp_;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
     */
    @Override
    public StatusOrBuilder getStatusRespOrBuilder() {
        return getStatusResp();
    }

    public static final int OUTPUT_DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString outputData_;

    /**
     * <code>bytes output_data = 2;</code>
     *
     * @return The outputData.
     */
    @Override
    public com.google.protobuf.ByteString getOutputData() {
        return outputData_;
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (statusResp_ != null) {
            output.writeMessage(1, getStatusResp());
        }
        if (!outputData_.isEmpty()) {
            output.writeBytes(2, outputData_);
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (statusResp_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, getStatusResp());
        }
        if (!outputData_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(2, outputData_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof ActionResp)) {
            return super.equals(obj);
        }
        ActionResp other = (ActionResp) obj;

        if (hasStatusResp() != other.hasStatusResp()) return false;
        if (hasStatusResp()) {
            if (!getStatusResp()
                    .equals(other.getStatusResp())) return false;
        }
        if (!getOutputData()
                .equals(other.getOutputData())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasStatusResp()) {
            hash = (37 * hash) + STATUS_RESP_FIELD_NUMBER;
            hash = (53 * hash) + getStatusResp().hashCode();
        }
        hash = (37 * hash) + OUTPUT_DATA_FIELD_NUMBER;
        hash = (53 * hash) + getOutputData().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static ActionResp parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static ActionResp parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ActionResp parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static ActionResp parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ActionResp parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static ActionResp parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ActionResp parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static ActionResp parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ActionResp parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static ActionResp parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static ActionResp parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static ActionResp parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(ActionResp prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code tr451_vomci_nbi_message.v1.ActionResp}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:tr451_vomci_nbi_message.v1.ActionResp)
            ActionRespOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_ActionResp_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_ActionResp_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ActionResp.class, Builder.class);
        }

        // Construct using org.broadband_forum.obbaa.dhcp.message.gpb.message.ActionResp.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            if (statusRespBuilder_ == null) {
                statusResp_ = null;
            } else {
                statusResp_ = null;
                statusRespBuilder_ = null;
            }
            outputData_ = com.google.protobuf.ByteString.EMPTY;

            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_ActionResp_descriptor;
        }

        @Override
        public ActionResp getDefaultInstanceForType() {
            return ActionResp.getDefaultInstance();
        }

        @Override
        public ActionResp build() {
            ActionResp result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public ActionResp buildPartial() {
            ActionResp result = new ActionResp(this);
            if (statusRespBuilder_ == null) {
                result.statusResp_ = statusResp_;
            } else {
                result.statusResp_ = statusRespBuilder_.build();
            }
            result.outputData_ = outputData_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof ActionResp) {
                return mergeFrom((ActionResp) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(ActionResp other) {
            if (other == ActionResp.getDefaultInstance()) return this;
            if (other.hasStatusResp()) {
                mergeStatusResp(other.getStatusResp());
            }
            if (other.getOutputData() != com.google.protobuf.ByteString.EMPTY) {
                setOutputData(other.getOutputData());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            ActionResp parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (ActionResp) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private Status statusResp_;
        private com.google.protobuf.SingleFieldBuilderV3<
                Status, Status.Builder, StatusOrBuilder> statusRespBuilder_;

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         *
         * @return Whether the statusResp field is set.
         */
        public boolean hasStatusResp() {
            return statusRespBuilder_ != null || statusResp_ != null;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         *
         * @return The statusResp.
         */
        public Status getStatusResp() {
            if (statusRespBuilder_ == null) {
                return statusResp_ == null ? Status.getDefaultInstance() : statusResp_;
            } else {
                return statusRespBuilder_.getMessage();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         */
        public Builder setStatusResp(Status value) {
            if (statusRespBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                statusResp_ = value;
                onChanged();
            } else {
                statusRespBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         */
        public Builder setStatusResp(
                Status.Builder builderForValue) {
            if (statusRespBuilder_ == null) {
                statusResp_ = builderForValue.build();
                onChanged();
            } else {
                statusRespBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         */
        public Builder mergeStatusResp(Status value) {
            if (statusRespBuilder_ == null) {
                if (statusResp_ != null) {
                    statusResp_ =
                            Status.newBuilder(statusResp_).mergeFrom(value).buildPartial();
                } else {
                    statusResp_ = value;
                }
                onChanged();
            } else {
                statusRespBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         */
        public Builder clearStatusResp() {
            if (statusRespBuilder_ == null) {
                statusResp_ = null;
                onChanged();
            } else {
                statusResp_ = null;
                statusRespBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         */
        public Status.Builder getStatusRespBuilder() {

            onChanged();
            return getStatusRespFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         */
        public StatusOrBuilder getStatusRespOrBuilder() {
            if (statusRespBuilder_ != null) {
                return statusRespBuilder_.getMessageOrBuilder();
            } else {
                return statusResp_ == null ?
                        Status.getDefaultInstance() : statusResp_;
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                Status, Status.Builder, StatusOrBuilder>
        getStatusRespFieldBuilder() {
            if (statusRespBuilder_ == null) {
                statusRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        Status, Status.Builder, StatusOrBuilder>(
                        getStatusResp(),
                        getParentForChildren(),
                        isClean());
                statusResp_ = null;
            }
            return statusRespBuilder_;
        }

        private com.google.protobuf.ByteString outputData_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <code>bytes output_data = 2;</code>
         *
         * @return The outputData.
         */
        @Override
        public com.google.protobuf.ByteString getOutputData() {
            return outputData_;
        }

        /**
         * <code>bytes output_data = 2;</code>
         *
         * @param value The outputData to set.
         * @return This builder for chaining.
         */
        public Builder setOutputData(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            outputData_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>bytes output_data = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearOutputData() {

            outputData_ = getDefaultInstance().getOutputData();
            onChanged();
            return this;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:tr451_vomci_nbi_message.v1.ActionResp)
    }

    // @@protoc_insertion_point(class_scope:tr451_vomci_nbi_message.v1.ActionResp)
    private static final ActionResp DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new ActionResp();
    }

    public static ActionResp getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ActionResp>
            PARSER = new com.google.protobuf.AbstractParser<ActionResp>() {
        @Override
        public ActionResp parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new ActionResp(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<ActionResp> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ActionResp> getParserForType() {
        return PARSER;
    }

    @Override
    public ActionResp getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

