// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.dhcp.message.gpb.message;

/**
 * <pre>
 * Type of error as defined in RFC 6241 section 4.3
 * </pre>
 * <p>
 * Protobuf type {@code tr451_vomci_nbi_message.v1.Error}
 */
public final class Error extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:tr451_vomci_nbi_message.v1.Error)
        ErrorOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Error.newBuilder() to construct.
    private Error(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Error() {
        errorType_ = "";
        errorTag_ = "";
        errorSeverity_ = "";
        errorAppTag_ = "";
        errorPath_ = "";
        errorMessage_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
        return new Error();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private Error(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        String s = input.readStringRequireUtf8();

                        errorType_ = s;
                        break;
                    }
                    case 18: {
                        String s = input.readStringRequireUtf8();

                        errorTag_ = s;
                        break;
                    }
                    case 26: {
                        String s = input.readStringRequireUtf8();

                        errorSeverity_ = s;
                        break;
                    }
                    case 34: {
                        String s = input.readStringRequireUtf8();

                        errorAppTag_ = s;
                        break;
                    }
                    case 42: {
                        String s = input.readStringRequireUtf8();

                        errorPath_ = s;
                        break;
                    }
                    case 50: {
                        String s = input.readStringRequireUtf8();

                        errorMessage_ = s;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Error_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Error_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Error.class, Builder.class);
    }

    public static final int ERROR_TYPE_FIELD_NUMBER = 1;
    private volatile Object errorType_;

    /**
     * <pre>
     * Error type defined in RFC 6241
     * </pre>
     *
     * <code>string error_type = 1;</code>
     *
     * @return The errorType.
     */
    @Override
    public String getErrorType() {
        Object ref = errorType_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            errorType_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * Error type defined in RFC 6241
     * </pre>
     *
     * <code>string error_type = 1;</code>
     *
     * @return The bytes for errorType.
     */
    @Override
    public com.google.protobuf.ByteString
    getErrorTypeBytes() {
        Object ref = errorType_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            errorType_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ERROR_TAG_FIELD_NUMBER = 2;
    private volatile Object errorTag_;

    /**
     * <pre>
     * Appendix B
     * </pre>
     *
     * <code>string error_tag = 2;</code>
     *
     * @return The errorTag.
     */
    @Override
    public String getErrorTag() {
        Object ref = errorTag_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            errorTag_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * Appendix B
     * </pre>
     *
     * <code>string error_tag = 2;</code>
     *
     * @return The bytes for errorTag.
     */
    @Override
    public com.google.protobuf.ByteString
    getErrorTagBytes() {
        Object ref = errorTag_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            errorTag_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ERROR_SEVERITY_FIELD_NUMBER = 3;
    private volatile Object errorSeverity_;

    /**
     * <pre>
     * Appendix B
     * </pre>
     *
     * <code>string error_severity = 3;</code>
     *
     * @return The errorSeverity.
     */
    @Override
    public String getErrorSeverity() {
        Object ref = errorSeverity_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            errorSeverity_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * Appendix B
     * </pre>
     *
     * <code>string error_severity = 3;</code>
     *
     * @return The bytes for errorSeverity.
     */
    @Override
    public com.google.protobuf.ByteString
    getErrorSeverityBytes() {
        Object ref = errorSeverity_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            errorSeverity_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ERROR_APP_TAG_FIELD_NUMBER = 4;
    private volatile Object errorAppTag_;

    /**
     * <pre>
     * Appendix B
     * </pre>
     *
     * <code>string error_app_tag = 4;</code>
     *
     * @return The errorAppTag.
     */
    @Override
    public String getErrorAppTag() {
        Object ref = errorAppTag_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            errorAppTag_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * Appendix B
     * </pre>
     *
     * <code>string error_app_tag = 4;</code>
     *
     * @return The bytes for errorAppTag.
     */
    @Override
    public com.google.protobuf.ByteString
    getErrorAppTagBytes() {
        Object ref = errorAppTag_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            errorAppTag_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ERROR_PATH_FIELD_NUMBER = 5;
    private volatile Object errorPath_;

    /**
     * <pre>
     * Appendix B
     * </pre>
     *
     * <code>string error_path = 5;</code>
     *
     * @return The errorPath.
     */
    @Override
    public String getErrorPath() {
        Object ref = errorPath_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            errorPath_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * Appendix B
     * </pre>
     *
     * <code>string error_path = 5;</code>
     *
     * @return The bytes for errorPath.
     */
    @Override
    public com.google.protobuf.ByteString
    getErrorPathBytes() {
        Object ref = errorPath_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            errorPath_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int ERROR_MESSAGE_FIELD_NUMBER = 6;
    private volatile Object errorMessage_;

    /**
     * <pre>
     * Appendix B
     * </pre>
     *
     * <code>string error_message = 6;</code>
     *
     * @return The errorMessage.
     */
    @Override
    public String getErrorMessage() {
        Object ref = errorMessage_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            errorMessage_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * Appendix B
     * </pre>
     *
     * <code>string error_message = 6;</code>
     *
     * @return The bytes for errorMessage.
     */
    @Override
    public com.google.protobuf.ByteString
    getErrorMessageBytes() {
        Object ref = errorMessage_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            errorMessage_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getErrorTypeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, errorType_);
        }
        if (!getErrorTagBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorTag_);
        }
        if (!getErrorSeverityBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorSeverity_);
        }
        if (!getErrorAppTagBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, errorAppTag_);
        }
        if (!getErrorPathBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, errorPath_);
        }
        if (!getErrorMessageBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 6, errorMessage_);
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getErrorTypeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, errorType_);
        }
        if (!getErrorTagBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorTag_);
        }
        if (!getErrorSeverityBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorSeverity_);
        }
        if (!getErrorAppTagBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, errorAppTag_);
        }
        if (!getErrorPathBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, errorPath_);
        }
        if (!getErrorMessageBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, errorMessage_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof Error)) {
            return super.equals(obj);
        }
        Error other = (Error) obj;

        if (!getErrorType()
                .equals(other.getErrorType())) return false;
        if (!getErrorTag()
                .equals(other.getErrorTag())) return false;
        if (!getErrorSeverity()
                .equals(other.getErrorSeverity())) return false;
        if (!getErrorAppTag()
                .equals(other.getErrorAppTag())) return false;
        if (!getErrorPath()
                .equals(other.getErrorPath())) return false;
        if (!getErrorMessage()
                .equals(other.getErrorMessage())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ERROR_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorType().hashCode();
        hash = (37 * hash) + ERROR_TAG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorTag().hashCode();
        hash = (37 * hash) + ERROR_SEVERITY_FIELD_NUMBER;
        hash = (53 * hash) + getErrorSeverity().hashCode();
        hash = (37 * hash) + ERROR_APP_TAG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorAppTag().hashCode();
        hash = (37 * hash) + ERROR_PATH_FIELD_NUMBER;
        hash = (53 * hash) + getErrorPath().hashCode();
        hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMessage().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static Error parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Error parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Error parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Error parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Error parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Error parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Error parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Error parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Error parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static Error parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Error parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Error parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Error prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * Type of error as defined in RFC 6241 section 4.3
     * </pre>
     * <p>
     * Protobuf type {@code tr451_vomci_nbi_message.v1.Error}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:tr451_vomci_nbi_message.v1.Error)
            ErrorOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Error_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Error_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Error.class, Builder.class);
        }

        // Construct using org.broadband_forum.obbaa.dhcp.message.gpb.message.Error.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            errorType_ = "";

            errorTag_ = "";

            errorSeverity_ = "";

            errorAppTag_ = "";

            errorPath_ = "";

            errorMessage_ = "";

            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Error_descriptor;
        }

        @Override
        public Error getDefaultInstanceForType() {
            return Error.getDefaultInstance();
        }

        @Override
        public Error build() {
            Error result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public Error buildPartial() {
            Error result = new Error(this);
            result.errorType_ = errorType_;
            result.errorTag_ = errorTag_;
            result.errorSeverity_ = errorSeverity_;
            result.errorAppTag_ = errorAppTag_;
            result.errorPath_ = errorPath_;
            result.errorMessage_ = errorMessage_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof Error) {
                return mergeFrom((Error) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(Error other) {
            if (other == Error.getDefaultInstance()) return this;
            if (!other.getErrorType().isEmpty()) {
                errorType_ = other.errorType_;
                onChanged();
            }
            if (!other.getErrorTag().isEmpty()) {
                errorTag_ = other.errorTag_;
                onChanged();
            }
            if (!other.getErrorSeverity().isEmpty()) {
                errorSeverity_ = other.errorSeverity_;
                onChanged();
            }
            if (!other.getErrorAppTag().isEmpty()) {
                errorAppTag_ = other.errorAppTag_;
                onChanged();
            }
            if (!other.getErrorPath().isEmpty()) {
                errorPath_ = other.errorPath_;
                onChanged();
            }
            if (!other.getErrorMessage().isEmpty()) {
                errorMessage_ = other.errorMessage_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Error parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (Error) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private Object errorType_ = "";

        /**
         * <pre>
         * Error type defined in RFC 6241
         * </pre>
         *
         * <code>string error_type = 1;</code>
         *
         * @return The errorType.
         */
        public String getErrorType() {
            Object ref = errorType_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                errorType_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * Error type defined in RFC 6241
         * </pre>
         *
         * <code>string error_type = 1;</code>
         *
         * @return The bytes for errorType.
         */
        public com.google.protobuf.ByteString
        getErrorTypeBytes() {
            Object ref = errorType_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                errorType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * Error type defined in RFC 6241
         * </pre>
         *
         * <code>string error_type = 1;</code>
         *
         * @param value The errorType to set.
         * @return This builder for chaining.
         */
        public Builder setErrorType(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            errorType_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Error type defined in RFC 6241
         * </pre>
         *
         * <code>string error_type = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearErrorType() {

            errorType_ = getDefaultInstance().getErrorType();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Error type defined in RFC 6241
         * </pre>
         *
         * <code>string error_type = 1;</code>
         *
         * @param value The bytes for errorType to set.
         * @return This builder for chaining.
         */
        public Builder setErrorTypeBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            errorType_ = value;
            onChanged();
            return this;
        }

        private Object errorTag_ = "";

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_tag = 2;</code>
         *
         * @return The errorTag.
         */
        public String getErrorTag() {
            Object ref = errorTag_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                errorTag_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_tag = 2;</code>
         *
         * @return The bytes for errorTag.
         */
        public com.google.protobuf.ByteString
        getErrorTagBytes() {
            Object ref = errorTag_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                errorTag_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_tag = 2;</code>
         *
         * @param value The errorTag to set.
         * @return This builder for chaining.
         */
        public Builder setErrorTag(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            errorTag_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_tag = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearErrorTag() {

            errorTag_ = getDefaultInstance().getErrorTag();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_tag = 2;</code>
         *
         * @param value The bytes for errorTag to set.
         * @return This builder for chaining.
         */
        public Builder setErrorTagBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            errorTag_ = value;
            onChanged();
            return this;
        }

        private Object errorSeverity_ = "";

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_severity = 3;</code>
         *
         * @return The errorSeverity.
         */
        public String getErrorSeverity() {
            Object ref = errorSeverity_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                errorSeverity_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_severity = 3;</code>
         *
         * @return The bytes for errorSeverity.
         */
        public com.google.protobuf.ByteString
        getErrorSeverityBytes() {
            Object ref = errorSeverity_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                errorSeverity_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_severity = 3;</code>
         *
         * @param value The errorSeverity to set.
         * @return This builder for chaining.
         */
        public Builder setErrorSeverity(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            errorSeverity_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_severity = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearErrorSeverity() {

            errorSeverity_ = getDefaultInstance().getErrorSeverity();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_severity = 3;</code>
         *
         * @param value The bytes for errorSeverity to set.
         * @return This builder for chaining.
         */
        public Builder setErrorSeverityBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            errorSeverity_ = value;
            onChanged();
            return this;
        }

        private Object errorAppTag_ = "";

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_app_tag = 4;</code>
         *
         * @return The errorAppTag.
         */
        public String getErrorAppTag() {
            Object ref = errorAppTag_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                errorAppTag_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_app_tag = 4;</code>
         *
         * @return The bytes for errorAppTag.
         */
        public com.google.protobuf.ByteString
        getErrorAppTagBytes() {
            Object ref = errorAppTag_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                errorAppTag_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_app_tag = 4;</code>
         *
         * @param value The errorAppTag to set.
         * @return This builder for chaining.
         */
        public Builder setErrorAppTag(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            errorAppTag_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_app_tag = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearErrorAppTag() {

            errorAppTag_ = getDefaultInstance().getErrorAppTag();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_app_tag = 4;</code>
         *
         * @param value The bytes for errorAppTag to set.
         * @return This builder for chaining.
         */
        public Builder setErrorAppTagBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            errorAppTag_ = value;
            onChanged();
            return this;
        }

        private Object errorPath_ = "";

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_path = 5;</code>
         *
         * @return The errorPath.
         */
        public String getErrorPath() {
            Object ref = errorPath_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                errorPath_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_path = 5;</code>
         *
         * @return The bytes for errorPath.
         */
        public com.google.protobuf.ByteString
        getErrorPathBytes() {
            Object ref = errorPath_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                errorPath_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_path = 5;</code>
         *
         * @param value The errorPath to set.
         * @return This builder for chaining.
         */
        public Builder setErrorPath(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            errorPath_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_path = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearErrorPath() {

            errorPath_ = getDefaultInstance().getErrorPath();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_path = 5;</code>
         *
         * @param value The bytes for errorPath to set.
         * @return This builder for chaining.
         */
        public Builder setErrorPathBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            errorPath_ = value;
            onChanged();
            return this;
        }

        private Object errorMessage_ = "";

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_message = 6;</code>
         *
         * @return The errorMessage.
         */
        public String getErrorMessage() {
            Object ref = errorMessage_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                errorMessage_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_message = 6;</code>
         *
         * @return The bytes for errorMessage.
         */
        public com.google.protobuf.ByteString
        getErrorMessageBytes() {
            Object ref = errorMessage_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                errorMessage_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_message = 6;</code>
         *
         * @param value The errorMessage to set.
         * @return This builder for chaining.
         */
        public Builder setErrorMessage(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            errorMessage_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_message = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearErrorMessage() {

            errorMessage_ = getDefaultInstance().getErrorMessage();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Appendix B
         * </pre>
         *
         * <code>string error_message = 6;</code>
         *
         * @param value The bytes for errorMessage to set.
         * @return This builder for chaining.
         */
        public Builder setErrorMessageBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            errorMessage_ = value;
            onChanged();
            return this;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:tr451_vomci_nbi_message.v1.Error)
    }

    // @@protoc_insertion_point(class_scope:tr451_vomci_nbi_message.v1.Error)
    private static final Error DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new Error();
    }

    public static Error getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Error>
            PARSER = new com.google.protobuf.AbstractParser<Error>() {
        @Override
        public Error parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Error(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<Error> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Error> getParserForType() {
        return PARSER;
    }

    @Override
    public Error getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

