// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.dhcp.message.gpb.message;

/**
 * Protobuf type {@code tr451_vomci_nbi_message.v1.GetDataResp}
 */
public final class GetDataResp extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:tr451_vomci_nbi_message.v1.GetDataResp)
        GetDataRespOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use GetDataResp.newBuilder() to construct.
    private GetDataResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private GetDataResp() {
        data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
        return new GetDataResp();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private GetDataResp(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        Status.Builder subBuilder = null;
                        if (statusResp_ != null) {
                            subBuilder = statusResp_.toBuilder();
                        }
                        statusResp_ = input.readMessage(Status.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(statusResp_);
                            statusResp_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 18: {

                        data_ = input.readBytes();
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_GetDataResp_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_GetDataResp_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        GetDataResp.class, Builder.class);
    }

    public static final int STATUS_RESP_FIELD_NUMBER = 1;
    private Status statusResp_;

    /**
     * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
     *
     * @return Whether the statusResp field is set.
     */
    @Override
    public boolean hasStatusResp() {
        return statusResp_ != null;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
     *
     * @return The statusResp.
     */
    @Override
    public Status getStatusResp() {
        return statusResp_ == null ? Status.getDefaultInstance() : statusResp_;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
     */
    @Override
    public StatusOrBuilder getStatusRespOrBuilder() {
        return getStatusResp();
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;

    /**
     * <code>bytes data = 2;</code>
     *
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
        return data_;
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (statusResp_ != null) {
            output.writeMessage(1, getStatusResp());
        }
        if (!data_.isEmpty()) {
            output.writeBytes(2, data_);
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (statusResp_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, getStatusResp());
        }
        if (!data_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(2, data_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof GetDataResp)) {
            return super.equals(obj);
        }
        GetDataResp other = (GetDataResp) obj;

        if (hasStatusResp() != other.hasStatusResp()) return false;
        if (hasStatusResp()) {
            if (!getStatusResp()
                    .equals(other.getStatusResp())) return false;
        }
        if (!getData()
                .equals(other.getData())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasStatusResp()) {
            hash = (37 * hash) + STATUS_RESP_FIELD_NUMBER;
            hash = (53 * hash) + getStatusResp().hashCode();
        }
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static GetDataResp parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static GetDataResp parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static GetDataResp parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static GetDataResp parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static GetDataResp parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static GetDataResp parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static GetDataResp parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static GetDataResp parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static GetDataResp parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static GetDataResp parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static GetDataResp parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static GetDataResp parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(GetDataResp prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code tr451_vomci_nbi_message.v1.GetDataResp}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:tr451_vomci_nbi_message.v1.GetDataResp)
            GetDataRespOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_GetDataResp_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_GetDataResp_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            GetDataResp.class, Builder.class);
        }

        // Construct using org.broadband_forum.obbaa.dhcp.message.gpb.message.GetDataResp.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            if (statusRespBuilder_ == null) {
                statusResp_ = null;
            } else {
                statusResp_ = null;
                statusRespBuilder_ = null;
            }
            data_ = com.google.protobuf.ByteString.EMPTY;

            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_GetDataResp_descriptor;
        }

        @Override
        public GetDataResp getDefaultInstanceForType() {
            return GetDataResp.getDefaultInstance();
        }

        @Override
        public GetDataResp build() {
            GetDataResp result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public GetDataResp buildPartial() {
            GetDataResp result = new GetDataResp(this);
            if (statusRespBuilder_ == null) {
                result.statusResp_ = statusResp_;
            } else {
                result.statusResp_ = statusRespBuilder_.build();
            }
            result.data_ = data_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof GetDataResp) {
                return mergeFrom((GetDataResp) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(GetDataResp other) {
            if (other == GetDataResp.getDefaultInstance()) return this;
            if (other.hasStatusResp()) {
                mergeStatusResp(other.getStatusResp());
            }
            if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
                setData(other.getData());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            GetDataResp parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (GetDataResp) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private Status statusResp_;
        private com.google.protobuf.SingleFieldBuilderV3<
                Status, Status.Builder, StatusOrBuilder> statusRespBuilder_;

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         *
         * @return Whether the statusResp field is set.
         */
        public boolean hasStatusResp() {
            return statusRespBuilder_ != null || statusResp_ != null;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         *
         * @return The statusResp.
         */
        public Status getStatusResp() {
            if (statusRespBuilder_ == null) {
                return statusResp_ == null ? Status.getDefaultInstance() : statusResp_;
            } else {
                return statusRespBuilder_.getMessage();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         */
        public Builder setStatusResp(Status value) {
            if (statusRespBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                statusResp_ = value;
                onChanged();
            } else {
                statusRespBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         */
        public Builder setStatusResp(
                Status.Builder builderForValue) {
            if (statusRespBuilder_ == null) {
                statusResp_ = builderForValue.build();
                onChanged();
            } else {
                statusRespBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         */
        public Builder mergeStatusResp(Status value) {
            if (statusRespBuilder_ == null) {
                if (statusResp_ != null) {
                    statusResp_ =
                            Status.newBuilder(statusResp_).mergeFrom(value).buildPartial();
                } else {
                    statusResp_ = value;
                }
                onChanged();
            } else {
                statusRespBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         */
        public Builder clearStatusResp() {
            if (statusRespBuilder_ == null) {
                statusResp_ = null;
                onChanged();
            } else {
                statusResp_ = null;
                statusRespBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         */
        public Status.Builder getStatusRespBuilder() {

            onChanged();
            return getStatusRespFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         */
        public StatusOrBuilder getStatusRespOrBuilder() {
            if (statusRespBuilder_ != null) {
                return statusRespBuilder_.getMessageOrBuilder();
            } else {
                return statusResp_ == null ?
                        Status.getDefaultInstance() : statusResp_;
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Status status_resp = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                Status, Status.Builder, StatusOrBuilder>
        getStatusRespFieldBuilder() {
            if (statusRespBuilder_ == null) {
                statusRespBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        Status, Status.Builder, StatusOrBuilder>(
                        getStatusResp(),
                        getParentForChildren(),
                        isClean());
                statusResp_ = null;
            }
            return statusRespBuilder_;
        }

        private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <code>bytes data = 2;</code>
         *
         * @return The data.
         */
        @Override
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        /**
         * <code>bytes data = 2;</code>
         *
         * @param value The data to set.
         * @return This builder for chaining.
         */
        public Builder setData(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }

            data_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>bytes data = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearData() {

            data_ = getDefaultInstance().getData();
            onChanged();
            return this;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:tr451_vomci_nbi_message.v1.GetDataResp)
    }

    // @@protoc_insertion_point(class_scope:tr451_vomci_nbi_message.v1.GetDataResp)
    private static final GetDataResp DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new GetDataResp();
    }

    public static GetDataResp getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetDataResp>
            PARSER = new com.google.protobuf.AbstractParser<GetDataResp>() {
        @Override
        public GetDataResp parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new GetDataResp(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<GetDataResp> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetDataResp> getParserForType() {
        return PARSER;
    }

    @Override
    public GetDataResp getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

