// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.dhcp.message.gpb.message;

/**
 * Protobuf type {@code tr451_vomci_nbi_message.v1.GetData}
 */
public final class GetData extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:tr451_vomci_nbi_message.v1.GetData)
        GetDataOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use GetData.newBuilder() to construct.
    private GetData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private GetData() {
        filter_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
        return new GetData();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private GetData(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                            filter_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                            mutable_bitField0_ |= 0x00000001;
                        }
                        filter_.add(input.readBytes());
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) != 0)) {
                filter_ = java.util.Collections.unmodifiableList(filter_); // C
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_GetData_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_GetData_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        GetData.class, Builder.class);
    }

    public static final int FILTER_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> filter_;

    /**
     * <code>repeated bytes filter = 1;</code>
     *
     * @return A list containing the filter.
     */
    @Override
    public java.util.List<com.google.protobuf.ByteString>
    getFilterList() {
        return filter_;
    }

    /**
     * <code>repeated bytes filter = 1;</code>
     *
     * @return The count of filter.
     */
    public int getFilterCount() {
        return filter_.size();
    }

    /**
     * <code>repeated bytes filter = 1;</code>
     *
     * @param index The index of the element to return.
     * @return The filter at the given index.
     */
    public com.google.protobuf.ByteString getFilter(int index) {
        return filter_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        for (int i = 0; i < filter_.size(); i++) {
            output.writeBytes(1, filter_.get(i));
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        {
            int dataSize = 0;
            for (int i = 0; i < filter_.size(); i++) {
                dataSize += com.google.protobuf.CodedOutputStream
                        .computeBytesSizeNoTag(filter_.get(i));
            }
            size += dataSize;
            size += 1 * getFilterList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof GetData)) {
            return super.equals(obj);
        }
        GetData other = (GetData) obj;

        if (!getFilterList()
                .equals(other.getFilterList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getFilterCount() > 0) {
            hash = (37 * hash) + FILTER_FIELD_NUMBER;
            hash = (53 * hash) + getFilterList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static GetData parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static GetData parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static GetData parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static GetData parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static GetData parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static GetData parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static GetData parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static GetData parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static GetData parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static GetData parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static GetData parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static GetData parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(GetData prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code tr451_vomci_nbi_message.v1.GetData}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:tr451_vomci_nbi_message.v1.GetData)
            GetDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_GetData_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_GetData_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            GetData.class, Builder.class);
        }

        // Construct using org.broadband_forum.obbaa.dhcp.message.gpb.message.GetData.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            filter_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_GetData_descriptor;
        }

        @Override
        public GetData getDefaultInstanceForType() {
            return GetData.getDefaultInstance();
        }

        @Override
        public GetData build() {
            GetData result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public GetData buildPartial() {
            GetData result = new GetData(this);
            int from_bitField0_ = bitField0_;
            if (((bitField0_ & 0x00000001) != 0)) {
                filter_ = java.util.Collections.unmodifiableList(filter_);
                bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.filter_ = filter_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof GetData) {
                return mergeFrom((GetData) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(GetData other) {
            if (other == GetData.getDefaultInstance()) return this;
            if (!other.filter_.isEmpty()) {
                if (filter_.isEmpty()) {
                    filter_ = other.filter_;
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    ensureFilterIsMutable();
                    filter_.addAll(other.filter_);
                }
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            GetData parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (GetData) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private java.util.List<com.google.protobuf.ByteString> filter_ = java.util.Collections.emptyList();

        private void ensureFilterIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
                filter_ = new java.util.ArrayList<com.google.protobuf.ByteString>(filter_);
                bitField0_ |= 0x00000001;
            }
        }

        /**
         * <code>repeated bytes filter = 1;</code>
         *
         * @return A list containing the filter.
         */
        public java.util.List<com.google.protobuf.ByteString>
        getFilterList() {
            return ((bitField0_ & 0x00000001) != 0) ?
                    java.util.Collections.unmodifiableList(filter_) : filter_;
        }

        /**
         * <code>repeated bytes filter = 1;</code>
         *
         * @return The count of filter.
         */
        public int getFilterCount() {
            return filter_.size();
        }

        /**
         * <code>repeated bytes filter = 1;</code>
         *
         * @param index The index of the element to return.
         * @return The filter at the given index.
         */
        public com.google.protobuf.ByteString getFilter(int index) {
            return filter_.get(index);
        }

        /**
         * <code>repeated bytes filter = 1;</code>
         *
         * @param index The index to set the value at.
         * @param value The filter to set.
         * @return This builder for chaining.
         */
        public Builder setFilter(
                int index, com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureFilterIsMutable();
            filter_.set(index, value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated bytes filter = 1;</code>
         *
         * @param value The filter to add.
         * @return This builder for chaining.
         */
        public Builder addFilter(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureFilterIsMutable();
            filter_.add(value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated bytes filter = 1;</code>
         *
         * @param values The filter to add.
         * @return This builder for chaining.
         */
        public Builder addAllFilter(
                Iterable<? extends com.google.protobuf.ByteString> values) {
            ensureFilterIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                    values, filter_);
            onChanged();
            return this;
        }

        /**
         * <code>repeated bytes filter = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearFilter() {
            filter_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:tr451_vomci_nbi_message.v1.GetData)
    }

    // @@protoc_insertion_point(class_scope:tr451_vomci_nbi_message.v1.GetData)
    private static final GetData DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new GetData();
    }

    public static GetData getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetData>
            PARSER = new com.google.protobuf.AbstractParser<GetData>() {
        @Override
        public GetData parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new GetData(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<GetData> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<GetData> getParserForType() {
        return PARSER;
    }

    @Override
    public GetData getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

