// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.dhcp.message.gpb.message;

/**
 * Protobuf type {@code tr451_vomci_nbi_message.v1.Header}
 */
public final class Header extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:tr451_vomci_nbi_message.v1.Header)
        HeaderOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Header() {
        msgId_ = "";
        senderName_ = "";
        recipientName_ = "";
        objectType_ = 0;
        objectName_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
        return new Header();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private Header(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        String s = input.readStringRequireUtf8();

                        msgId_ = s;
                        break;
                    }
                    case 18: {
                        String s = input.readStringRequireUtf8();

                        senderName_ = s;
                        break;
                    }
                    case 26: {
                        String s = input.readStringRequireUtf8();

                        recipientName_ = s;
                        break;
                    }
                    case 32: {
                        int rawValue = input.readEnum();

                        objectType_ = rawValue;
                        break;
                    }
                    case 42: {
                        String s = input.readStringRequireUtf8();

                        objectName_ = s;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Header_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Header_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Header.class, Builder.class);
    }

    /**
     * Protobuf enum {@code tr451_vomci_nbi_message.v1.Header.OBJECT_TYPE}
     */
    public enum OBJECT_TYPE
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>ONU = 0;</code>
         */
        ONU(0),
        /**
         * <code>VOMCI_FUNCTION = 1;</code>
         */
        VOMCI_FUNCTION(1),
        /**
         * <code>VOMCI_PROXY = 2;</code>
         */
        VOMCI_PROXY(2),
        /**
         * <code>VOLTMF = 3;</code>
         */
        VOLTMF(3),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>ONU = 0;</code>
         */
        public static final int ONU_VALUE = 0;
        /**
         * <code>VOMCI_FUNCTION = 1;</code>
         */
        public static final int VOMCI_FUNCTION_VALUE = 1;
        /**
         * <code>VOMCI_PROXY = 2;</code>
         */
        public static final int VOMCI_PROXY_VALUE = 2;
        /**
         * <code>VOLTMF = 3;</code>
         */
        public static final int VOLTMF_VALUE = 3;


        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static OBJECT_TYPE valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static OBJECT_TYPE forNumber(int value) {
            switch (value) {
                case 0:
                    return ONU;
                case 1:
                    return VOMCI_FUNCTION;
                case 2:
                    return VOMCI_PROXY;
                case 3:
                    return VOLTMF;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<OBJECT_TYPE>
        internalGetValueMap() {
            return internalValueMap;
        }

        private static final com.google.protobuf.Internal.EnumLiteMap<
                OBJECT_TYPE> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<OBJECT_TYPE>() {
                    public OBJECT_TYPE findValueByNumber(int number) {
                        return OBJECT_TYPE.forNumber(number);
                    }
                };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            if (this == UNRECOGNIZED) {
                throw new IllegalStateException(
                        "Can't get the descriptor of an unrecognized enum value.");
            }
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return Header.getDescriptor().getEnumTypes().get(0);
        }

        private static final OBJECT_TYPE[] VALUES = values();

        public static OBJECT_TYPE valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        private final int value;

        private OBJECT_TYPE(int value) {
            this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:tr451_vomci_nbi_message.v1.Header.OBJECT_TYPE)
    }

    public static final int MSG_ID_FIELD_NUMBER = 1;
    private volatile Object msgId_;

    /**
     * <pre>
     * Message identifier to
     * </pre>
     *
     * <code>string msg_id = 1;</code>
     *
     * @return The msgId.
     */
    @Override
    public String getMsgId() {
        Object ref = msgId_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            msgId_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * Message identifier to
     * </pre>
     *
     * <code>string msg_id = 1;</code>
     *
     * @return The bytes for msgId.
     */
    @Override
    public com.google.protobuf.ByteString
    getMsgIdBytes() {
        Object ref = msgId_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            msgId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int SENDER_NAME_FIELD_NUMBER = 2;
    private volatile Object senderName_;

    /**
     * <pre>
     * 1) Identify requests and notifications
     * 2) Correlate requests and response
     * </pre>
     *
     * <code>string sender_name = 2;</code>
     *
     * @return The senderName.
     */
    @Override
    public String getSenderName() {
        Object ref = senderName_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            senderName_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 1) Identify requests and notifications
     * 2) Correlate requests and response
     * </pre>
     *
     * <code>string sender_name = 2;</code>
     *
     * @return The bytes for senderName.
     */
    @Override
    public com.google.protobuf.ByteString
    getSenderNameBytes() {
        Object ref = senderName_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            senderName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int RECIPIENT_NAME_FIELD_NUMBER = 3;
    private volatile Object recipientName_;

    /**
     * <pre>
     * originated the message
     * </pre>
     *
     * <code>string recipient_name = 3;</code>
     *
     * @return The recipientName.
     */
    @Override
    public String getRecipientName() {
        Object ref = recipientName_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            recipientName_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * originated the message
     * </pre>
     *
     * <code>string recipient_name = 3;</code>
     *
     * @return The bytes for recipientName.
     */
    @Override
    public com.google.protobuf.ByteString
    getRecipientNameBytes() {
        Object ref = recipientName_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            recipientName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int OBJECT_TYPE_FIELD_NUMBER = 4;
    private int objectType_;

    /**
     * <pre>
     * receive the request
     * </pre>
     *
     * <code>.tr451_vomci_nbi_message.v1.Header.OBJECT_TYPE object_type = 4;</code>
     *
     * @return The enum numeric value on the wire for objectType.
     */
    @Override
    public int getObjectTypeValue() {
        return objectType_;
    }

    /**
     * <pre>
     * receive the request
     * </pre>
     *
     * <code>.tr451_vomci_nbi_message.v1.Header.OBJECT_TYPE object_type = 4;</code>
     *
     * @return The objectType.
     */
    @Override
    public OBJECT_TYPE getObjectType() {
        @SuppressWarnings("deprecation")
        OBJECT_TYPE result = OBJECT_TYPE.valueOf(objectType_);
        return result == null ? OBJECT_TYPE.UNRECOGNIZED : result;
    }

    public static final int OBJECT_NAME_FIELD_NUMBER = 5;
    private volatile Object objectName_;

    /**
     * <pre>
     * resource that is subject of the message
     * </pre>
     *
     * <code>string object_name = 5;</code>
     *
     * @return The objectName.
     */
    @Override
    public String getObjectName() {
        Object ref = objectName_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            objectName_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * resource that is subject of the message
     * </pre>
     *
     * <code>string object_name = 5;</code>
     *
     * @return The bytes for objectName.
     */
    @Override
    public com.google.protobuf.ByteString
    getObjectNameBytes() {
        Object ref = objectName_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            objectName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getMsgIdBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgId_);
        }
        if (!getSenderNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, senderName_);
        }
        if (!getRecipientNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, recipientName_);
        }
        if (objectType_ != OBJECT_TYPE.ONU.getNumber()) {
            output.writeEnum(4, objectType_);
        }
        if (!getObjectNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, objectName_);
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getMsgIdBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgId_);
        }
        if (!getSenderNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, senderName_);
        }
        if (!getRecipientNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, recipientName_);
        }
        if (objectType_ != OBJECT_TYPE.ONU.getNumber()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeEnumSize(4, objectType_);
        }
        if (!getObjectNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, objectName_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof Header)) {
            return super.equals(obj);
        }
        Header other = (Header) obj;

        if (!getMsgId()
                .equals(other.getMsgId())) return false;
        if (!getSenderName()
                .equals(other.getSenderName())) return false;
        if (!getRecipientName()
                .equals(other.getRecipientName())) return false;
        if (objectType_ != other.objectType_) return false;
        if (!getObjectName()
                .equals(other.getObjectName())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
        hash = (53 * hash) + getMsgId().hashCode();
        hash = (37 * hash) + SENDER_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getSenderName().hashCode();
        hash = (37 * hash) + RECIPIENT_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getRecipientName().hashCode();
        hash = (37 * hash) + OBJECT_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + objectType_;
        hash = (37 * hash) + OBJECT_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getObjectName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static Header parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Header parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Header parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Header parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Header parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Header parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Header parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Header parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Header parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static Header parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Header parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Header parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Header prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code tr451_vomci_nbi_message.v1.Header}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:tr451_vomci_nbi_message.v1.Header)
            HeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Header_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Header_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Header.class, Builder.class);
        }

        // Construct using org.broadband_forum.obbaa.dhcp.message.gpb.message.Header.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            msgId_ = "";

            senderName_ = "";

            recipientName_ = "";

            objectType_ = 0;

            objectName_ = "";

            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Header_descriptor;
        }

        @Override
        public Header getDefaultInstanceForType() {
            return Header.getDefaultInstance();
        }

        @Override
        public Header build() {
            Header result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public Header buildPartial() {
            Header result = new Header(this);
            result.msgId_ = msgId_;
            result.senderName_ = senderName_;
            result.recipientName_ = recipientName_;
            result.objectType_ = objectType_;
            result.objectName_ = objectName_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof Header) {
                return mergeFrom((Header) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(Header other) {
            if (other == Header.getDefaultInstance()) return this;
            if (!other.getMsgId().isEmpty()) {
                msgId_ = other.msgId_;
                onChanged();
            }
            if (!other.getSenderName().isEmpty()) {
                senderName_ = other.senderName_;
                onChanged();
            }
            if (!other.getRecipientName().isEmpty()) {
                recipientName_ = other.recipientName_;
                onChanged();
            }
            if (other.objectType_ != 0) {
                setObjectTypeValue(other.getObjectTypeValue());
            }
            if (!other.getObjectName().isEmpty()) {
                objectName_ = other.objectName_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Header parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (Header) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private Object msgId_ = "";

        /**
         * <pre>
         * Message identifier to
         * </pre>
         *
         * <code>string msg_id = 1;</code>
         *
         * @return The msgId.
         */
        public String getMsgId() {
            Object ref = msgId_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                msgId_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * Message identifier to
         * </pre>
         *
         * <code>string msg_id = 1;</code>
         *
         * @return The bytes for msgId.
         */
        public com.google.protobuf.ByteString
        getMsgIdBytes() {
            Object ref = msgId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                msgId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * Message identifier to
         * </pre>
         *
         * <code>string msg_id = 1;</code>
         *
         * @param value The msgId to set.
         * @return This builder for chaining.
         */
        public Builder setMsgId(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            msgId_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Message identifier to
         * </pre>
         *
         * <code>string msg_id = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMsgId() {

            msgId_ = getDefaultInstance().getMsgId();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Message identifier to
         * </pre>
         *
         * <code>string msg_id = 1;</code>
         *
         * @param value The bytes for msgId to set.
         * @return This builder for chaining.
         */
        public Builder setMsgIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            msgId_ = value;
            onChanged();
            return this;
        }

        private Object senderName_ = "";

        /**
         * <pre>
         * 1) Identify requests and notifications
         * 2) Correlate requests and response
         * </pre>
         *
         * <code>string sender_name = 2;</code>
         *
         * @return The senderName.
         */
        public String getSenderName() {
            Object ref = senderName_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                senderName_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * 1) Identify requests and notifications
         * 2) Correlate requests and response
         * </pre>
         *
         * <code>string sender_name = 2;</code>
         *
         * @return The bytes for senderName.
         */
        public com.google.protobuf.ByteString
        getSenderNameBytes() {
            Object ref = senderName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                senderName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 1) Identify requests and notifications
         * 2) Correlate requests and response
         * </pre>
         *
         * <code>string sender_name = 2;</code>
         *
         * @param value The senderName to set.
         * @return This builder for chaining.
         */
        public Builder setSenderName(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            senderName_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 1) Identify requests and notifications
         * 2) Correlate requests and response
         * </pre>
         *
         * <code>string sender_name = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSenderName() {

            senderName_ = getDefaultInstance().getSenderName();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 1) Identify requests and notifications
         * 2) Correlate requests and response
         * </pre>
         *
         * <code>string sender_name = 2;</code>
         *
         * @param value The bytes for senderName to set.
         * @return This builder for chaining.
         */
        public Builder setSenderNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            senderName_ = value;
            onChanged();
            return this;
        }

        private Object recipientName_ = "";

        /**
         * <pre>
         * originated the message
         * </pre>
         *
         * <code>string recipient_name = 3;</code>
         *
         * @return The recipientName.
         */
        public String getRecipientName() {
            Object ref = recipientName_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                recipientName_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * originated the message
         * </pre>
         *
         * <code>string recipient_name = 3;</code>
         *
         * @return The bytes for recipientName.
         */
        public com.google.protobuf.ByteString
        getRecipientNameBytes() {
            Object ref = recipientName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                recipientName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * originated the message
         * </pre>
         *
         * <code>string recipient_name = 3;</code>
         *
         * @param value The recipientName to set.
         * @return This builder for chaining.
         */
        public Builder setRecipientName(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            recipientName_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * originated the message
         * </pre>
         *
         * <code>string recipient_name = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearRecipientName() {

            recipientName_ = getDefaultInstance().getRecipientName();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * originated the message
         * </pre>
         *
         * <code>string recipient_name = 3;</code>
         *
         * @param value The bytes for recipientName to set.
         * @return This builder for chaining.
         */
        public Builder setRecipientNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            recipientName_ = value;
            onChanged();
            return this;
        }

        private int objectType_ = 0;

        /**
         * <pre>
         * receive the request
         * </pre>
         *
         * <code>.tr451_vomci_nbi_message.v1.Header.OBJECT_TYPE object_type = 4;</code>
         *
         * @return The enum numeric value on the wire for objectType.
         */
        @Override
        public int getObjectTypeValue() {
            return objectType_;
        }

        /**
         * <pre>
         * receive the request
         * </pre>
         *
         * <code>.tr451_vomci_nbi_message.v1.Header.OBJECT_TYPE object_type = 4;</code>
         *
         * @param value The enum numeric value on the wire for objectType to set.
         * @return This builder for chaining.
         */
        public Builder setObjectTypeValue(int value) {

            objectType_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * receive the request
         * </pre>
         *
         * <code>.tr451_vomci_nbi_message.v1.Header.OBJECT_TYPE object_type = 4;</code>
         *
         * @return The objectType.
         */
        @Override
        public OBJECT_TYPE getObjectType() {
            @SuppressWarnings("deprecation")
            OBJECT_TYPE result = OBJECT_TYPE.valueOf(objectType_);
            return result == null ? OBJECT_TYPE.UNRECOGNIZED : result;
        }

        /**
         * <pre>
         * receive the request
         * </pre>
         *
         * <code>.tr451_vomci_nbi_message.v1.Header.OBJECT_TYPE object_type = 4;</code>
         *
         * @param value The objectType to set.
         * @return This builder for chaining.
         */
        public Builder setObjectType(OBJECT_TYPE value) {
            if (value == null) {
                throw new NullPointerException();
            }

            objectType_ = value.getNumber();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * receive the request
         * </pre>
         *
         * <code>.tr451_vomci_nbi_message.v1.Header.OBJECT_TYPE object_type = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearObjectType() {

            objectType_ = 0;
            onChanged();
            return this;
        }

        private Object objectName_ = "";

        /**
         * <pre>
         * resource that is subject of the message
         * </pre>
         *
         * <code>string object_name = 5;</code>
         *
         * @return The objectName.
         */
        public String getObjectName() {
            Object ref = objectName_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                objectName_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <pre>
         * resource that is subject of the message
         * </pre>
         *
         * <code>string object_name = 5;</code>
         *
         * @return The bytes for objectName.
         */
        public com.google.protobuf.ByteString
        getObjectNameBytes() {
            Object ref = objectName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                objectName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * resource that is subject of the message
         * </pre>
         *
         * <code>string object_name = 5;</code>
         *
         * @param value The objectName to set.
         * @return This builder for chaining.
         */
        public Builder setObjectName(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            objectName_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * resource that is subject of the message
         * </pre>
         *
         * <code>string object_name = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearObjectName() {

            objectName_ = getDefaultInstance().getObjectName();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * resource that is subject of the message
         * </pre>
         *
         * <code>string object_name = 5;</code>
         *
         * @param value The bytes for objectName to set.
         * @return This builder for chaining.
         */
        public Builder setObjectNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            objectName_ = value;
            onChanged();
            return this;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:tr451_vomci_nbi_message.v1.Header)
    }

    // @@protoc_insertion_point(class_scope:tr451_vomci_nbi_message.v1.Header)
    private static final Header DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new Header();
    }

    public static Header getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Header>
            PARSER = new com.google.protobuf.AbstractParser<Header>() {
        @Override
        public Header parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Header(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<Header> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Header> getParserForType() {
        return PARSER;
    }

    @Override
    public Header getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

