// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.dhcp.message.gpb.message;

/**
 * Protobuf type {@code tr451_vomci_nbi_message.v1.Msg}
 */
public final class Msg extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:tr451_vomci_nbi_message.v1.Msg)
        MsgOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Msg() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
        return new Msg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private Msg(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        Header.Builder subBuilder = null;
                        if (header_ != null) {
                            subBuilder = header_.toBuilder();
                        }
                        header_ = input.readMessage(Header.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(header_);
                            header_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    case 18: {
                        Body.Builder subBuilder = null;
                        if (body_ != null) {
                            subBuilder = body_.toBuilder();
                        }
                        body_ = input.readMessage(Body.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom(body_);
                            body_ = subBuilder.buildPartial();
                        }

                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Msg_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Msg_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Msg.class, Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private Header header_;

    /**
     * <code>.tr451_vomci_nbi_message.v1.Header header = 1;</code>
     *
     * @return Whether the header field is set.
     */
    @Override
    public boolean hasHeader() {
        return header_ != null;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.Header header = 1;</code>
     *
     * @return The header.
     */
    @Override
    public Header getHeader() {
        return header_ == null ? Header.getDefaultInstance() : header_;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.Header header = 1;</code>
     */
    @Override
    public HeaderOrBuilder getHeaderOrBuilder() {
        return getHeader();
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private Body body_;

    /**
     * <code>.tr451_vomci_nbi_message.v1.Body body = 2;</code>
     *
     * @return Whether the body field is set.
     */
    @Override
    public boolean hasBody() {
        return body_ != null;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.Body body = 2;</code>
     *
     * @return The body.
     */
    @Override
    public Body getBody() {
        return body_ == null ? Body.getDefaultInstance() : body_;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.Body body = 2;</code>
     */
    @Override
    public BodyOrBuilder getBodyOrBuilder() {
        return getBody();
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (header_ != null) {
            output.writeMessage(1, getHeader());
        }
        if (body_ != null) {
            output.writeMessage(2, getBody());
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (header_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, getHeader());
        }
        if (body_ != null) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(2, getBody());
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof Msg)) {
            return super.equals(obj);
        }
        Msg other = (Msg) obj;

        if (hasHeader() != other.hasHeader()) return false;
        if (hasHeader()) {
            if (!getHeader()
                    .equals(other.getHeader())) return false;
        }
        if (hasBody() != other.hasBody()) return false;
        if (hasBody()) {
            if (!getBody()
                    .equals(other.getBody())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasHeader()) {
            hash = (37 * hash) + HEADER_FIELD_NUMBER;
            hash = (53 * hash) + getHeader().hashCode();
        }
        if (hasBody()) {
            hash = (37 * hash) + BODY_FIELD_NUMBER;
            hash = (53 * hash) + getBody().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static Msg parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Msg parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Msg parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Msg parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Msg parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Msg parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Msg parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Msg parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Msg parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static Msg parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Msg parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Msg parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Msg prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code tr451_vomci_nbi_message.v1.Msg}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:tr451_vomci_nbi_message.v1.Msg)
            MsgOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Msg_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Msg_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Msg.class, Builder.class);
        }

        // Construct using org.broadband_forum.obbaa.dhcp.message.gpb.message.Msg.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            if (headerBuilder_ == null) {
                header_ = null;
            } else {
                header_ = null;
                headerBuilder_ = null;
            }
            if (bodyBuilder_ == null) {
                body_ = null;
            } else {
                body_ = null;
                bodyBuilder_ = null;
            }
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Msg_descriptor;
        }

        @Override
        public Msg getDefaultInstanceForType() {
            return Msg.getDefaultInstance();
        }

        @Override
        public Msg build() {
            Msg result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public Msg buildPartial() {
            Msg result = new Msg(this);
            if (headerBuilder_ == null) {
                result.header_ = header_;
            } else {
                result.header_ = headerBuilder_.build();
            }
            if (bodyBuilder_ == null) {
                result.body_ = body_;
            } else {
                result.body_ = bodyBuilder_.build();
            }
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof Msg) {
                return mergeFrom((Msg) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(Msg other) {
            if (other == Msg.getDefaultInstance()) return this;
            if (other.hasHeader()) {
                mergeHeader(other.getHeader());
            }
            if (other.hasBody()) {
                mergeBody(other.getBody());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Msg parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (Msg) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private Header header_;
        private com.google.protobuf.SingleFieldBuilderV3<
                Header, Header.Builder, HeaderOrBuilder> headerBuilder_;

        /**
         * <code>.tr451_vomci_nbi_message.v1.Header header = 1;</code>
         *
         * @return Whether the header field is set.
         */
        public boolean hasHeader() {
            return headerBuilder_ != null || header_ != null;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Header header = 1;</code>
         *
         * @return The header.
         */
        public Header getHeader() {
            if (headerBuilder_ == null) {
                return header_ == null ? Header.getDefaultInstance() : header_;
            } else {
                return headerBuilder_.getMessage();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Header header = 1;</code>
         */
        public Builder setHeader(Header value) {
            if (headerBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                header_ = value;
                onChanged();
            } else {
                headerBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Header header = 1;</code>
         */
        public Builder setHeader(
                Header.Builder builderForValue) {
            if (headerBuilder_ == null) {
                header_ = builderForValue.build();
                onChanged();
            } else {
                headerBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Header header = 1;</code>
         */
        public Builder mergeHeader(Header value) {
            if (headerBuilder_ == null) {
                if (header_ != null) {
                    header_ =
                            Header.newBuilder(header_).mergeFrom(value).buildPartial();
                } else {
                    header_ = value;
                }
                onChanged();
            } else {
                headerBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Header header = 1;</code>
         */
        public Builder clearHeader() {
            if (headerBuilder_ == null) {
                header_ = null;
                onChanged();
            } else {
                header_ = null;
                headerBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Header header = 1;</code>
         */
        public Header.Builder getHeaderBuilder() {

            onChanged();
            return getHeaderFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Header header = 1;</code>
         */
        public HeaderOrBuilder getHeaderOrBuilder() {
            if (headerBuilder_ != null) {
                return headerBuilder_.getMessageOrBuilder();
            } else {
                return header_ == null ?
                        Header.getDefaultInstance() : header_;
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Header header = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                Header, Header.Builder, HeaderOrBuilder>
        getHeaderFieldBuilder() {
            if (headerBuilder_ == null) {
                headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        Header, Header.Builder, HeaderOrBuilder>(
                        getHeader(),
                        getParentForChildren(),
                        isClean());
                header_ = null;
            }
            return headerBuilder_;
        }

        private Body body_;
        private com.google.protobuf.SingleFieldBuilderV3<
                Body, Body.Builder, BodyOrBuilder> bodyBuilder_;

        /**
         * <code>.tr451_vomci_nbi_message.v1.Body body = 2;</code>
         *
         * @return Whether the body field is set.
         */
        public boolean hasBody() {
            return bodyBuilder_ != null || body_ != null;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Body body = 2;</code>
         *
         * @return The body.
         */
        public Body getBody() {
            if (bodyBuilder_ == null) {
                return body_ == null ? Body.getDefaultInstance() : body_;
            } else {
                return bodyBuilder_.getMessage();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Body body = 2;</code>
         */
        public Builder setBody(Body value) {
            if (bodyBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                body_ = value;
                onChanged();
            } else {
                bodyBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Body body = 2;</code>
         */
        public Builder setBody(
                Body.Builder builderForValue) {
            if (bodyBuilder_ == null) {
                body_ = builderForValue.build();
                onChanged();
            } else {
                bodyBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Body body = 2;</code>
         */
        public Builder mergeBody(Body value) {
            if (bodyBuilder_ == null) {
                if (body_ != null) {
                    body_ =
                            Body.newBuilder(body_).mergeFrom(value).buildPartial();
                } else {
                    body_ = value;
                }
                onChanged();
            } else {
                bodyBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Body body = 2;</code>
         */
        public Builder clearBody() {
            if (bodyBuilder_ == null) {
                body_ = null;
                onChanged();
            } else {
                body_ = null;
                bodyBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Body body = 2;</code>
         */
        public Body.Builder getBodyBuilder() {

            onChanged();
            return getBodyFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Body body = 2;</code>
         */
        public BodyOrBuilder getBodyOrBuilder() {
            if (bodyBuilder_ != null) {
                return bodyBuilder_.getMessageOrBuilder();
            } else {
                return body_ == null ?
                        Body.getDefaultInstance() : body_;
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Body body = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                Body, Body.Builder, BodyOrBuilder>
        getBodyFieldBuilder() {
            if (bodyBuilder_ == null) {
                bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        Body, Body.Builder, BodyOrBuilder>(
                        getBody(),
                        getParentForChildren(),
                        isClean());
                body_ = null;
            }
            return bodyBuilder_;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:tr451_vomci_nbi_message.v1.Msg)
    }

    // @@protoc_insertion_point(class_scope:tr451_vomci_nbi_message.v1.Msg)
    private static final Msg DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new Msg();
    }

    public static Msg getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg>
            PARSER = new com.google.protobuf.AbstractParser<Msg>() {
        @Override
        public Msg parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Msg(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
        return PARSER;
    }

    @Override
    public Msg getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

