// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.dhcp.message.gpb.message;

public interface MsgOrBuilder extends
        // @@protoc_insertion_point(interface_extends:tr451_vomci_nbi_message.v1.Msg)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tr451_vomci_nbi_message.v1.Header header = 1;</code>
     *
     * @return Whether the header field is set.
     */
    boolean hasHeader();

    /**
     * <code>.tr451_vomci_nbi_message.v1.Header header = 1;</code>
     *
     * @return The header.
     */
    Header getHeader();

    /**
     * <code>.tr451_vomci_nbi_message.v1.Header header = 1;</code>
     */
    HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>.tr451_vomci_nbi_message.v1.Body body = 2;</code>
     *
     * @return Whether the body field is set.
     */
    boolean hasBody();

    /**
     * <code>.tr451_vomci_nbi_message.v1.Body body = 2;</code>
     *
     * @return The body.
     */
    Body getBody();

    /**
     * <code>.tr451_vomci_nbi_message.v1.Body body = 2;</code>
     */
    BodyOrBuilder getBodyOrBuilder();
}
