// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.dhcp.message.gpb.message;

/**
 * Protobuf type {@code tr451_vomci_nbi_message.v1.Request}
 */
public final class Request extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:tr451_vomci_nbi_message.v1.Request)
        RequestOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Request() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
        return new Request();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private Request(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 18: {
                        Hello.Builder subBuilder = null;
                        if (reqTypeCase_ == 2) {
                            subBuilder = ((Hello) reqType_).toBuilder();
                        }
                        reqType_ =
                                input.readMessage(Hello.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom((Hello) reqType_);
                            reqType_ = subBuilder.buildPartial();
                        }
                        reqTypeCase_ = 2;
                        break;
                    }
                    case 26: {
                        GetData.Builder subBuilder = null;
                        if (reqTypeCase_ == 3) {
                            subBuilder = ((GetData) reqType_).toBuilder();
                        }
                        reqType_ =
                                input.readMessage(GetData.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom((GetData) reqType_);
                            reqType_ = subBuilder.buildPartial();
                        }
                        reqTypeCase_ = 3;
                        break;
                    }
                    case 34: {
                        ReplaceConfig.Builder subBuilder = null;
                        if (reqTypeCase_ == 4) {
                            subBuilder = ((ReplaceConfig) reqType_).toBuilder();
                        }
                        reqType_ =
                                input.readMessage(ReplaceConfig.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom((ReplaceConfig) reqType_);
                            reqType_ = subBuilder.buildPartial();
                        }
                        reqTypeCase_ = 4;
                        break;
                    }
                    case 42: {
                        UpdateConfig.Builder subBuilder = null;
                        if (reqTypeCase_ == 5) {
                            subBuilder = ((UpdateConfig) reqType_).toBuilder();
                        }
                        reqType_ =
                                input.readMessage(UpdateConfig.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom((UpdateConfig) reqType_);
                            reqType_ = subBuilder.buildPartial();
                        }
                        reqTypeCase_ = 5;
                        break;
                    }
                    case 50: {
                        RPC.Builder subBuilder = null;
                        if (reqTypeCase_ == 6) {
                            subBuilder = ((RPC) reqType_).toBuilder();
                        }
                        reqType_ =
                                input.readMessage(RPC.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom((RPC) reqType_);
                            reqType_ = subBuilder.buildPartial();
                        }
                        reqTypeCase_ = 6;
                        break;
                    }
                    case 58: {
                        Action.Builder subBuilder = null;
                        if (reqTypeCase_ == 7) {
                            subBuilder = ((Action) reqType_).toBuilder();
                        }
                        reqType_ =
                                input.readMessage(Action.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom((Action) reqType_);
                            reqType_ = subBuilder.buildPartial();
                        }
                        reqTypeCase_ = 7;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Request_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Request_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Request.class, Builder.class);
    }

    private int reqTypeCase_ = 0;
    private Object reqType_;

    public enum ReqTypeCase
            implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
        HELLO(2),
        GET_DATA(3),
        REPLACE_CONFIG(4),
        UPDATE_CONFIG(5),
        RPC(6),
        ACTION(7),
        REQTYPE_NOT_SET(0);
        private final int value;

        private ReqTypeCase(int value) {
            this.value = value;
        }

        /**
         * @param value The number of the enum to look for.
         * @return The enum associated with the given number.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static ReqTypeCase valueOf(int value) {
            return forNumber(value);
        }

        public static ReqTypeCase forNumber(int value) {
            switch (value) {
                case 2:
                    return HELLO;
                case 3:
                    return GET_DATA;
                case 4:
                    return REPLACE_CONFIG;
                case 5:
                    return UPDATE_CONFIG;
                case 6:
                    return RPC;
                case 7:
                    return ACTION;
                case 0:
                    return REQTYPE_NOT_SET;
                default:
                    return null;
            }
        }

        public int getNumber() {
            return this.value;
        }
    }

    ;

    public ReqTypeCase
    getReqTypeCase() {
        return ReqTypeCase.forNumber(
                reqTypeCase_);
    }

    public static final int HELLO_FIELD_NUMBER = 2;

    /**
     * <code>.tr451_vomci_nbi_message.v1.Hello hello = 2;</code>
     *
     * @return Whether the hello field is set.
     */
    @Override
    public boolean hasHello() {
        return reqTypeCase_ == 2;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.Hello hello = 2;</code>
     *
     * @return The hello.
     */
    @Override
    public Hello getHello() {
        if (reqTypeCase_ == 2) {
            return (Hello) reqType_;
        }
        return Hello.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.Hello hello = 2;</code>
     */
    @Override
    public HelloOrBuilder getHelloOrBuilder() {
        if (reqTypeCase_ == 2) {
            return (Hello) reqType_;
        }
        return Hello.getDefaultInstance();
    }

    public static final int GET_DATA_FIELD_NUMBER = 3;

    /**
     * <code>.tr451_vomci_nbi_message.v1.GetData get_data = 3;</code>
     *
     * @return Whether the getData field is set.
     */
    @Override
    public boolean hasGetData() {
        return reqTypeCase_ == 3;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.GetData get_data = 3;</code>
     *
     * @return The getData.
     */
    @Override
    public GetData getGetData() {
        if (reqTypeCase_ == 3) {
            return (GetData) reqType_;
        }
        return GetData.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.GetData get_data = 3;</code>
     */
    @Override
    public GetDataOrBuilder getGetDataOrBuilder() {
        if (reqTypeCase_ == 3) {
            return (GetData) reqType_;
        }
        return GetData.getDefaultInstance();
    }

    public static final int REPLACE_CONFIG_FIELD_NUMBER = 4;

    /**
     * <code>.tr451_vomci_nbi_message.v1.ReplaceConfig replace_config = 4;</code>
     *
     * @return Whether the replaceConfig field is set.
     */
    @Override
    public boolean hasReplaceConfig() {
        return reqTypeCase_ == 4;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.ReplaceConfig replace_config = 4;</code>
     *
     * @return The replaceConfig.
     */
    @Override
    public ReplaceConfig getReplaceConfig() {
        if (reqTypeCase_ == 4) {
            return (ReplaceConfig) reqType_;
        }
        return ReplaceConfig.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.ReplaceConfig replace_config = 4;</code>
     */
    @Override
    public ReplaceConfigOrBuilder getReplaceConfigOrBuilder() {
        if (reqTypeCase_ == 4) {
            return (ReplaceConfig) reqType_;
        }
        return ReplaceConfig.getDefaultInstance();
    }

    public static final int UPDATE_CONFIG_FIELD_NUMBER = 5;

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfig update_config = 5;</code>
     *
     * @return Whether the updateConfig field is set.
     */
    @Override
    public boolean hasUpdateConfig() {
        return reqTypeCase_ == 5;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfig update_config = 5;</code>
     *
     * @return The updateConfig.
     */
    @Override
    public UpdateConfig getUpdateConfig() {
        if (reqTypeCase_ == 5) {
            return (UpdateConfig) reqType_;
        }
        return UpdateConfig.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfig update_config = 5;</code>
     */
    @Override
    public UpdateConfigOrBuilder getUpdateConfigOrBuilder() {
        if (reqTypeCase_ == 5) {
            return (UpdateConfig) reqType_;
        }
        return UpdateConfig.getDefaultInstance();
    }

    public static final int RPC_FIELD_NUMBER = 6;

    /**
     * <code>.tr451_vomci_nbi_message.v1.RPC rpc = 6;</code>
     *
     * @return Whether the rpc field is set.
     */
    @Override
    public boolean hasRpc() {
        return reqTypeCase_ == 6;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.RPC rpc = 6;</code>
     *
     * @return The rpc.
     */
    @Override
    public RPC getRpc() {
        if (reqTypeCase_ == 6) {
            return (RPC) reqType_;
        }
        return RPC.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.RPC rpc = 6;</code>
     */
    @Override
    public RPCOrBuilder getRpcOrBuilder() {
        if (reqTypeCase_ == 6) {
            return (RPC) reqType_;
        }
        return RPC.getDefaultInstance();
    }

    public static final int ACTION_FIELD_NUMBER = 7;

    /**
     * <code>.tr451_vomci_nbi_message.v1.Action action = 7;</code>
     *
     * @return Whether the action field is set.
     */
    @Override
    public boolean hasAction() {
        return reqTypeCase_ == 7;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.Action action = 7;</code>
     *
     * @return The action.
     */
    @Override
    public Action getAction() {
        if (reqTypeCase_ == 7) {
            return (Action) reqType_;
        }
        return Action.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.Action action = 7;</code>
     */
    @Override
    public ActionOrBuilder getActionOrBuilder() {
        if (reqTypeCase_ == 7) {
            return (Action) reqType_;
        }
        return Action.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (reqTypeCase_ == 2) {
            output.writeMessage(2, (Hello) reqType_);
        }
        if (reqTypeCase_ == 3) {
            output.writeMessage(3, (GetData) reqType_);
        }
        if (reqTypeCase_ == 4) {
            output.writeMessage(4, (ReplaceConfig) reqType_);
        }
        if (reqTypeCase_ == 5) {
            output.writeMessage(5, (UpdateConfig) reqType_);
        }
        if (reqTypeCase_ == 6) {
            output.writeMessage(6, (RPC) reqType_);
        }
        if (reqTypeCase_ == 7) {
            output.writeMessage(7, (Action) reqType_);
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (reqTypeCase_ == 2) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(2, (Hello) reqType_);
        }
        if (reqTypeCase_ == 3) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(3, (GetData) reqType_);
        }
        if (reqTypeCase_ == 4) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(4, (ReplaceConfig) reqType_);
        }
        if (reqTypeCase_ == 5) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(5, (UpdateConfig) reqType_);
        }
        if (reqTypeCase_ == 6) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(6, (RPC) reqType_);
        }
        if (reqTypeCase_ == 7) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(7, (Action) reqType_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof Request)) {
            return super.equals(obj);
        }
        Request other = (Request) obj;

        if (!getReqTypeCase().equals(other.getReqTypeCase())) return false;
        switch (reqTypeCase_) {
            case 2:
                if (!getHello()
                        .equals(other.getHello())) return false;
                break;
            case 3:
                if (!getGetData()
                        .equals(other.getGetData())) return false;
                break;
            case 4:
                if (!getReplaceConfig()
                        .equals(other.getReplaceConfig())) return false;
                break;
            case 5:
                if (!getUpdateConfig()
                        .equals(other.getUpdateConfig())) return false;
                break;
            case 6:
                if (!getRpc()
                        .equals(other.getRpc())) return false;
                break;
            case 7:
                if (!getAction()
                        .equals(other.getAction())) return false;
                break;
            case 0:
            default:
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        switch (reqTypeCase_) {
            case 2:
                hash = (37 * hash) + HELLO_FIELD_NUMBER;
                hash = (53 * hash) + getHello().hashCode();
                break;
            case 3:
                hash = (37 * hash) + GET_DATA_FIELD_NUMBER;
                hash = (53 * hash) + getGetData().hashCode();
                break;
            case 4:
                hash = (37 * hash) + REPLACE_CONFIG_FIELD_NUMBER;
                hash = (53 * hash) + getReplaceConfig().hashCode();
                break;
            case 5:
                hash = (37 * hash) + UPDATE_CONFIG_FIELD_NUMBER;
                hash = (53 * hash) + getUpdateConfig().hashCode();
                break;
            case 6:
                hash = (37 * hash) + RPC_FIELD_NUMBER;
                hash = (53 * hash) + getRpc().hashCode();
                break;
            case 7:
                hash = (37 * hash) + ACTION_FIELD_NUMBER;
                hash = (53 * hash) + getAction().hashCode();
                break;
            case 0:
            default:
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static Request parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Request parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Request parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Request parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Request parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Request parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Request parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Request parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Request parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static Request parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Request parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static Request parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Request prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code tr451_vomci_nbi_message.v1.Request}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:tr451_vomci_nbi_message.v1.Request)
            RequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Request_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Request_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Request.class, Builder.class);
        }

        // Construct using org.broadband_forum.obbaa.dhcp.message.gpb.message.Request.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            reqTypeCase_ = 0;
            reqType_ = null;
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_Request_descriptor;
        }

        @Override
        public Request getDefaultInstanceForType() {
            return Request.getDefaultInstance();
        }

        @Override
        public Request build() {
            Request result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public Request buildPartial() {
            Request result = new Request(this);
            if (reqTypeCase_ == 2) {
                if (helloBuilder_ == null) {
                    result.reqType_ = reqType_;
                } else {
                    result.reqType_ = helloBuilder_.build();
                }
            }
            if (reqTypeCase_ == 3) {
                if (getDataBuilder_ == null) {
                    result.reqType_ = reqType_;
                } else {
                    result.reqType_ = getDataBuilder_.build();
                }
            }
            if (reqTypeCase_ == 4) {
                if (replaceConfigBuilder_ == null) {
                    result.reqType_ = reqType_;
                } else {
                    result.reqType_ = replaceConfigBuilder_.build();
                }
            }
            if (reqTypeCase_ == 5) {
                if (updateConfigBuilder_ == null) {
                    result.reqType_ = reqType_;
                } else {
                    result.reqType_ = updateConfigBuilder_.build();
                }
            }
            if (reqTypeCase_ == 6) {
                if (rpcBuilder_ == null) {
                    result.reqType_ = reqType_;
                } else {
                    result.reqType_ = rpcBuilder_.build();
                }
            }
            if (reqTypeCase_ == 7) {
                if (actionBuilder_ == null) {
                    result.reqType_ = reqType_;
                } else {
                    result.reqType_ = actionBuilder_.build();
                }
            }
            result.reqTypeCase_ = reqTypeCase_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof Request) {
                return mergeFrom((Request) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(Request other) {
            if (other == Request.getDefaultInstance()) return this;
            switch (other.getReqTypeCase()) {
                case HELLO: {
                    mergeHello(other.getHello());
                    break;
                }
                case GET_DATA: {
                    mergeGetData(other.getGetData());
                    break;
                }
                case REPLACE_CONFIG: {
                    mergeReplaceConfig(other.getReplaceConfig());
                    break;
                }
                case UPDATE_CONFIG: {
                    mergeUpdateConfig(other.getUpdateConfig());
                    break;
                }
                case RPC: {
                    mergeRpc(other.getRpc());
                    break;
                }
                case ACTION: {
                    mergeAction(other.getAction());
                    break;
                }
                case REQTYPE_NOT_SET: {
                    break;
                }
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Request parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (Request) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int reqTypeCase_ = 0;
        private Object reqType_;

        public ReqTypeCase
        getReqTypeCase() {
            return ReqTypeCase.forNumber(
                    reqTypeCase_);
        }

        public Builder clearReqType() {
            reqTypeCase_ = 0;
            reqType_ = null;
            onChanged();
            return this;
        }


        private com.google.protobuf.SingleFieldBuilderV3<
                Hello, Hello.Builder, HelloOrBuilder> helloBuilder_;

        /**
         * <code>.tr451_vomci_nbi_message.v1.Hello hello = 2;</code>
         *
         * @return Whether the hello field is set.
         */
        @Override
        public boolean hasHello() {
            return reqTypeCase_ == 2;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Hello hello = 2;</code>
         *
         * @return The hello.
         */
        @Override
        public Hello getHello() {
            if (helloBuilder_ == null) {
                if (reqTypeCase_ == 2) {
                    return (Hello) reqType_;
                }
                return Hello.getDefaultInstance();
            } else {
                if (reqTypeCase_ == 2) {
                    return helloBuilder_.getMessage();
                }
                return Hello.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Hello hello = 2;</code>
         */
        public Builder setHello(Hello value) {
            if (helloBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                reqType_ = value;
                onChanged();
            } else {
                helloBuilder_.setMessage(value);
            }
            reqTypeCase_ = 2;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Hello hello = 2;</code>
         */
        public Builder setHello(
                Hello.Builder builderForValue) {
            if (helloBuilder_ == null) {
                reqType_ = builderForValue.build();
                onChanged();
            } else {
                helloBuilder_.setMessage(builderForValue.build());
            }
            reqTypeCase_ = 2;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Hello hello = 2;</code>
         */
        public Builder mergeHello(Hello value) {
            if (helloBuilder_ == null) {
                if (reqTypeCase_ == 2 &&
                        reqType_ != Hello.getDefaultInstance()) {
                    reqType_ = Hello.newBuilder((Hello) reqType_)
                            .mergeFrom(value).buildPartial();
                } else {
                    reqType_ = value;
                }
                onChanged();
            } else {
                if (reqTypeCase_ == 2) {
                    helloBuilder_.mergeFrom(value);
                }
                helloBuilder_.setMessage(value);
            }
            reqTypeCase_ = 2;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Hello hello = 2;</code>
         */
        public Builder clearHello() {
            if (helloBuilder_ == null) {
                if (reqTypeCase_ == 2) {
                    reqTypeCase_ = 0;
                    reqType_ = null;
                    onChanged();
                }
            } else {
                if (reqTypeCase_ == 2) {
                    reqTypeCase_ = 0;
                    reqType_ = null;
                }
                helloBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Hello hello = 2;</code>
         */
        public Hello.Builder getHelloBuilder() {
            return getHelloFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Hello hello = 2;</code>
         */
        @Override
        public HelloOrBuilder getHelloOrBuilder() {
            if ((reqTypeCase_ == 2) && (helloBuilder_ != null)) {
                return helloBuilder_.getMessageOrBuilder();
            } else {
                if (reqTypeCase_ == 2) {
                    return (Hello) reqType_;
                }
                return Hello.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Hello hello = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                Hello, Hello.Builder, HelloOrBuilder>
        getHelloFieldBuilder() {
            if (helloBuilder_ == null) {
                if (!(reqTypeCase_ == 2)) {
                    reqType_ = Hello.getDefaultInstance();
                }
                helloBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        Hello, Hello.Builder, HelloOrBuilder>(
                        (Hello) reqType_,
                        getParentForChildren(),
                        isClean());
                reqType_ = null;
            }
            reqTypeCase_ = 2;
            onChanged();
            ;
            return helloBuilder_;
        }

        private com.google.protobuf.SingleFieldBuilderV3<
                GetData, GetData.Builder, GetDataOrBuilder> getDataBuilder_;

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetData get_data = 3;</code>
         *
         * @return Whether the getData field is set.
         */
        @Override
        public boolean hasGetData() {
            return reqTypeCase_ == 3;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetData get_data = 3;</code>
         *
         * @return The getData.
         */
        @Override
        public GetData getGetData() {
            if (getDataBuilder_ == null) {
                if (reqTypeCase_ == 3) {
                    return (GetData) reqType_;
                }
                return GetData.getDefaultInstance();
            } else {
                if (reqTypeCase_ == 3) {
                    return getDataBuilder_.getMessage();
                }
                return GetData.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetData get_data = 3;</code>
         */
        public Builder setGetData(GetData value) {
            if (getDataBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                reqType_ = value;
                onChanged();
            } else {
                getDataBuilder_.setMessage(value);
            }
            reqTypeCase_ = 3;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetData get_data = 3;</code>
         */
        public Builder setGetData(
                GetData.Builder builderForValue) {
            if (getDataBuilder_ == null) {
                reqType_ = builderForValue.build();
                onChanged();
            } else {
                getDataBuilder_.setMessage(builderForValue.build());
            }
            reqTypeCase_ = 3;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetData get_data = 3;</code>
         */
        public Builder mergeGetData(GetData value) {
            if (getDataBuilder_ == null) {
                if (reqTypeCase_ == 3 &&
                        reqType_ != GetData.getDefaultInstance()) {
                    reqType_ = GetData.newBuilder((GetData) reqType_)
                            .mergeFrom(value).buildPartial();
                } else {
                    reqType_ = value;
                }
                onChanged();
            } else {
                if (reqTypeCase_ == 3) {
                    getDataBuilder_.mergeFrom(value);
                }
                getDataBuilder_.setMessage(value);
            }
            reqTypeCase_ = 3;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetData get_data = 3;</code>
         */
        public Builder clearGetData() {
            if (getDataBuilder_ == null) {
                if (reqTypeCase_ == 3) {
                    reqTypeCase_ = 0;
                    reqType_ = null;
                    onChanged();
                }
            } else {
                if (reqTypeCase_ == 3) {
                    reqTypeCase_ = 0;
                    reqType_ = null;
                }
                getDataBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetData get_data = 3;</code>
         */
        public GetData.Builder getGetDataBuilder() {
            return getGetDataFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetData get_data = 3;</code>
         */
        @Override
        public GetDataOrBuilder getGetDataOrBuilder() {
            if ((reqTypeCase_ == 3) && (getDataBuilder_ != null)) {
                return getDataBuilder_.getMessageOrBuilder();
            } else {
                if (reqTypeCase_ == 3) {
                    return (GetData) reqType_;
                }
                return GetData.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.GetData get_data = 3;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                GetData, GetData.Builder, GetDataOrBuilder>
        getGetDataFieldBuilder() {
            if (getDataBuilder_ == null) {
                if (!(reqTypeCase_ == 3)) {
                    reqType_ = GetData.getDefaultInstance();
                }
                getDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        GetData, GetData.Builder, GetDataOrBuilder>(
                        (GetData) reqType_,
                        getParentForChildren(),
                        isClean());
                reqType_ = null;
            }
            reqTypeCase_ = 3;
            onChanged();
            ;
            return getDataBuilder_;
        }

        private com.google.protobuf.SingleFieldBuilderV3<
                ReplaceConfig, ReplaceConfig.Builder, ReplaceConfigOrBuilder> replaceConfigBuilder_;

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfig replace_config = 4;</code>
         *
         * @return Whether the replaceConfig field is set.
         */
        @Override
        public boolean hasReplaceConfig() {
            return reqTypeCase_ == 4;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfig replace_config = 4;</code>
         *
         * @return The replaceConfig.
         */
        @Override
        public ReplaceConfig getReplaceConfig() {
            if (replaceConfigBuilder_ == null) {
                if (reqTypeCase_ == 4) {
                    return (ReplaceConfig) reqType_;
                }
                return ReplaceConfig.getDefaultInstance();
            } else {
                if (reqTypeCase_ == 4) {
                    return replaceConfigBuilder_.getMessage();
                }
                return ReplaceConfig.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfig replace_config = 4;</code>
         */
        public Builder setReplaceConfig(ReplaceConfig value) {
            if (replaceConfigBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                reqType_ = value;
                onChanged();
            } else {
                replaceConfigBuilder_.setMessage(value);
            }
            reqTypeCase_ = 4;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfig replace_config = 4;</code>
         */
        public Builder setReplaceConfig(
                ReplaceConfig.Builder builderForValue) {
            if (replaceConfigBuilder_ == null) {
                reqType_ = builderForValue.build();
                onChanged();
            } else {
                replaceConfigBuilder_.setMessage(builderForValue.build());
            }
            reqTypeCase_ = 4;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfig replace_config = 4;</code>
         */
        public Builder mergeReplaceConfig(ReplaceConfig value) {
            if (replaceConfigBuilder_ == null) {
                if (reqTypeCase_ == 4 &&
                        reqType_ != ReplaceConfig.getDefaultInstance()) {
                    reqType_ = ReplaceConfig.newBuilder((ReplaceConfig) reqType_)
                            .mergeFrom(value).buildPartial();
                } else {
                    reqType_ = value;
                }
                onChanged();
            } else {
                if (reqTypeCase_ == 4) {
                    replaceConfigBuilder_.mergeFrom(value);
                }
                replaceConfigBuilder_.setMessage(value);
            }
            reqTypeCase_ = 4;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfig replace_config = 4;</code>
         */
        public Builder clearReplaceConfig() {
            if (replaceConfigBuilder_ == null) {
                if (reqTypeCase_ == 4) {
                    reqTypeCase_ = 0;
                    reqType_ = null;
                    onChanged();
                }
            } else {
                if (reqTypeCase_ == 4) {
                    reqTypeCase_ = 0;
                    reqType_ = null;
                }
                replaceConfigBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfig replace_config = 4;</code>
         */
        public ReplaceConfig.Builder getReplaceConfigBuilder() {
            return getReplaceConfigFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfig replace_config = 4;</code>
         */
        @Override
        public ReplaceConfigOrBuilder getReplaceConfigOrBuilder() {
            if ((reqTypeCase_ == 4) && (replaceConfigBuilder_ != null)) {
                return replaceConfigBuilder_.getMessageOrBuilder();
            } else {
                if (reqTypeCase_ == 4) {
                    return (ReplaceConfig) reqType_;
                }
                return ReplaceConfig.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.ReplaceConfig replace_config = 4;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                ReplaceConfig, ReplaceConfig.Builder, ReplaceConfigOrBuilder>
        getReplaceConfigFieldBuilder() {
            if (replaceConfigBuilder_ == null) {
                if (!(reqTypeCase_ == 4)) {
                    reqType_ = ReplaceConfig.getDefaultInstance();
                }
                replaceConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        ReplaceConfig, ReplaceConfig.Builder, ReplaceConfigOrBuilder>(
                        (ReplaceConfig) reqType_,
                        getParentForChildren(),
                        isClean());
                reqType_ = null;
            }
            reqTypeCase_ = 4;
            onChanged();
            ;
            return replaceConfigBuilder_;
        }

        private com.google.protobuf.SingleFieldBuilderV3<
                UpdateConfig, UpdateConfig.Builder, UpdateConfigOrBuilder> updateConfigBuilder_;

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfig update_config = 5;</code>
         *
         * @return Whether the updateConfig field is set.
         */
        @Override
        public boolean hasUpdateConfig() {
            return reqTypeCase_ == 5;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfig update_config = 5;</code>
         *
         * @return The updateConfig.
         */
        @Override
        public UpdateConfig getUpdateConfig() {
            if (updateConfigBuilder_ == null) {
                if (reqTypeCase_ == 5) {
                    return (UpdateConfig) reqType_;
                }
                return UpdateConfig.getDefaultInstance();
            } else {
                if (reqTypeCase_ == 5) {
                    return updateConfigBuilder_.getMessage();
                }
                return UpdateConfig.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfig update_config = 5;</code>
         */
        public Builder setUpdateConfig(UpdateConfig value) {
            if (updateConfigBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                reqType_ = value;
                onChanged();
            } else {
                updateConfigBuilder_.setMessage(value);
            }
            reqTypeCase_ = 5;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfig update_config = 5;</code>
         */
        public Builder setUpdateConfig(
                UpdateConfig.Builder builderForValue) {
            if (updateConfigBuilder_ == null) {
                reqType_ = builderForValue.build();
                onChanged();
            } else {
                updateConfigBuilder_.setMessage(builderForValue.build());
            }
            reqTypeCase_ = 5;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfig update_config = 5;</code>
         */
        public Builder mergeUpdateConfig(UpdateConfig value) {
            if (updateConfigBuilder_ == null) {
                if (reqTypeCase_ == 5 &&
                        reqType_ != UpdateConfig.getDefaultInstance()) {
                    reqType_ = UpdateConfig.newBuilder((UpdateConfig) reqType_)
                            .mergeFrom(value).buildPartial();
                } else {
                    reqType_ = value;
                }
                onChanged();
            } else {
                if (reqTypeCase_ == 5) {
                    updateConfigBuilder_.mergeFrom(value);
                }
                updateConfigBuilder_.setMessage(value);
            }
            reqTypeCase_ = 5;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfig update_config = 5;</code>
         */
        public Builder clearUpdateConfig() {
            if (updateConfigBuilder_ == null) {
                if (reqTypeCase_ == 5) {
                    reqTypeCase_ = 0;
                    reqType_ = null;
                    onChanged();
                }
            } else {
                if (reqTypeCase_ == 5) {
                    reqTypeCase_ = 0;
                    reqType_ = null;
                }
                updateConfigBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfig update_config = 5;</code>
         */
        public UpdateConfig.Builder getUpdateConfigBuilder() {
            return getUpdateConfigFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfig update_config = 5;</code>
         */
        @Override
        public UpdateConfigOrBuilder getUpdateConfigOrBuilder() {
            if ((reqTypeCase_ == 5) && (updateConfigBuilder_ != null)) {
                return updateConfigBuilder_.getMessageOrBuilder();
            } else {
                if (reqTypeCase_ == 5) {
                    return (UpdateConfig) reqType_;
                }
                return UpdateConfig.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfig update_config = 5;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                UpdateConfig, UpdateConfig.Builder, UpdateConfigOrBuilder>
        getUpdateConfigFieldBuilder() {
            if (updateConfigBuilder_ == null) {
                if (!(reqTypeCase_ == 5)) {
                    reqType_ = UpdateConfig.getDefaultInstance();
                }
                updateConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        UpdateConfig, UpdateConfig.Builder, UpdateConfigOrBuilder>(
                        (UpdateConfig) reqType_,
                        getParentForChildren(),
                        isClean());
                reqType_ = null;
            }
            reqTypeCase_ = 5;
            onChanged();
            ;
            return updateConfigBuilder_;
        }

        private com.google.protobuf.SingleFieldBuilderV3<
                RPC, RPC.Builder, RPCOrBuilder> rpcBuilder_;

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPC rpc = 6;</code>
         *
         * @return Whether the rpc field is set.
         */
        @Override
        public boolean hasRpc() {
            return reqTypeCase_ == 6;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPC rpc = 6;</code>
         *
         * @return The rpc.
         */
        @Override
        public RPC getRpc() {
            if (rpcBuilder_ == null) {
                if (reqTypeCase_ == 6) {
                    return (RPC) reqType_;
                }
                return RPC.getDefaultInstance();
            } else {
                if (reqTypeCase_ == 6) {
                    return rpcBuilder_.getMessage();
                }
                return RPC.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPC rpc = 6;</code>
         */
        public Builder setRpc(RPC value) {
            if (rpcBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                reqType_ = value;
                onChanged();
            } else {
                rpcBuilder_.setMessage(value);
            }
            reqTypeCase_ = 6;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPC rpc = 6;</code>
         */
        public Builder setRpc(
                RPC.Builder builderForValue) {
            if (rpcBuilder_ == null) {
                reqType_ = builderForValue.build();
                onChanged();
            } else {
                rpcBuilder_.setMessage(builderForValue.build());
            }
            reqTypeCase_ = 6;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPC rpc = 6;</code>
         */
        public Builder mergeRpc(RPC value) {
            if (rpcBuilder_ == null) {
                if (reqTypeCase_ == 6 &&
                        reqType_ != RPC.getDefaultInstance()) {
                    reqType_ = RPC.newBuilder((RPC) reqType_)
                            .mergeFrom(value).buildPartial();
                } else {
                    reqType_ = value;
                }
                onChanged();
            } else {
                if (reqTypeCase_ == 6) {
                    rpcBuilder_.mergeFrom(value);
                }
                rpcBuilder_.setMessage(value);
            }
            reqTypeCase_ = 6;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPC rpc = 6;</code>
         */
        public Builder clearRpc() {
            if (rpcBuilder_ == null) {
                if (reqTypeCase_ == 6) {
                    reqTypeCase_ = 0;
                    reqType_ = null;
                    onChanged();
                }
            } else {
                if (reqTypeCase_ == 6) {
                    reqTypeCase_ = 0;
                    reqType_ = null;
                }
                rpcBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPC rpc = 6;</code>
         */
        public RPC.Builder getRpcBuilder() {
            return getRpcFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPC rpc = 6;</code>
         */
        @Override
        public RPCOrBuilder getRpcOrBuilder() {
            if ((reqTypeCase_ == 6) && (rpcBuilder_ != null)) {
                return rpcBuilder_.getMessageOrBuilder();
            } else {
                if (reqTypeCase_ == 6) {
                    return (RPC) reqType_;
                }
                return RPC.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.RPC rpc = 6;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                RPC, RPC.Builder, RPCOrBuilder>
        getRpcFieldBuilder() {
            if (rpcBuilder_ == null) {
                if (!(reqTypeCase_ == 6)) {
                    reqType_ = RPC.getDefaultInstance();
                }
                rpcBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        RPC, RPC.Builder, RPCOrBuilder>(
                        (RPC) reqType_,
                        getParentForChildren(),
                        isClean());
                reqType_ = null;
            }
            reqTypeCase_ = 6;
            onChanged();
            ;
            return rpcBuilder_;
        }

        private com.google.protobuf.SingleFieldBuilderV3<
                Action, Action.Builder, ActionOrBuilder> actionBuilder_;

        /**
         * <code>.tr451_vomci_nbi_message.v1.Action action = 7;</code>
         *
         * @return Whether the action field is set.
         */
        @Override
        public boolean hasAction() {
            return reqTypeCase_ == 7;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Action action = 7;</code>
         *
         * @return The action.
         */
        @Override
        public Action getAction() {
            if (actionBuilder_ == null) {
                if (reqTypeCase_ == 7) {
                    return (Action) reqType_;
                }
                return Action.getDefaultInstance();
            } else {
                if (reqTypeCase_ == 7) {
                    return actionBuilder_.getMessage();
                }
                return Action.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Action action = 7;</code>
         */
        public Builder setAction(Action value) {
            if (actionBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                reqType_ = value;
                onChanged();
            } else {
                actionBuilder_.setMessage(value);
            }
            reqTypeCase_ = 7;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Action action = 7;</code>
         */
        public Builder setAction(
                Action.Builder builderForValue) {
            if (actionBuilder_ == null) {
                reqType_ = builderForValue.build();
                onChanged();
            } else {
                actionBuilder_.setMessage(builderForValue.build());
            }
            reqTypeCase_ = 7;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Action action = 7;</code>
         */
        public Builder mergeAction(Action value) {
            if (actionBuilder_ == null) {
                if (reqTypeCase_ == 7 &&
                        reqType_ != Action.getDefaultInstance()) {
                    reqType_ = Action.newBuilder((Action) reqType_)
                            .mergeFrom(value).buildPartial();
                } else {
                    reqType_ = value;
                }
                onChanged();
            } else {
                if (reqTypeCase_ == 7) {
                    actionBuilder_.mergeFrom(value);
                }
                actionBuilder_.setMessage(value);
            }
            reqTypeCase_ = 7;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Action action = 7;</code>
         */
        public Builder clearAction() {
            if (actionBuilder_ == null) {
                if (reqTypeCase_ == 7) {
                    reqTypeCase_ = 0;
                    reqType_ = null;
                    onChanged();
                }
            } else {
                if (reqTypeCase_ == 7) {
                    reqTypeCase_ = 0;
                    reqType_ = null;
                }
                actionBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Action action = 7;</code>
         */
        public Action.Builder getActionBuilder() {
            return getActionFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Action action = 7;</code>
         */
        @Override
        public ActionOrBuilder getActionOrBuilder() {
            if ((reqTypeCase_ == 7) && (actionBuilder_ != null)) {
                return actionBuilder_.getMessageOrBuilder();
            } else {
                if (reqTypeCase_ == 7) {
                    return (Action) reqType_;
                }
                return Action.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.Action action = 7;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                Action, Action.Builder, ActionOrBuilder>
        getActionFieldBuilder() {
            if (actionBuilder_ == null) {
                if (!(reqTypeCase_ == 7)) {
                    reqType_ = Action.getDefaultInstance();
                }
                actionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        Action, Action.Builder, ActionOrBuilder>(
                        (Action) reqType_,
                        getParentForChildren(),
                        isClean());
                reqType_ = null;
            }
            reqTypeCase_ = 7;
            onChanged();
            ;
            return actionBuilder_;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:tr451_vomci_nbi_message.v1.Request)
    }

    // @@protoc_insertion_point(class_scope:tr451_vomci_nbi_message.v1.Request)
    private static final Request DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new Request();
    }

    public static Request getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
            PARSER = new com.google.protobuf.AbstractParser<Request>() {
        @Override
        public Request parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new Request(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<Request> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Request> getParserForType() {
        return PARSER;
    }

    @Override
    public Request getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

