// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.dhcp.message.gpb.message;

public interface RequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:tr451_vomci_nbi_message.v1.Request)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tr451_vomci_nbi_message.v1.Hello hello = 2;</code>
     *
     * @return Whether the hello field is set.
     */
    boolean hasHello();

    /**
     * <code>.tr451_vomci_nbi_message.v1.Hello hello = 2;</code>
     *
     * @return The hello.
     */
    Hello getHello();

    /**
     * <code>.tr451_vomci_nbi_message.v1.Hello hello = 2;</code>
     */
    HelloOrBuilder getHelloOrBuilder();

    /**
     * <code>.tr451_vomci_nbi_message.v1.GetData get_data = 3;</code>
     *
     * @return Whether the getData field is set.
     */
    boolean hasGetData();

    /**
     * <code>.tr451_vomci_nbi_message.v1.GetData get_data = 3;</code>
     *
     * @return The getData.
     */
    GetData getGetData();

    /**
     * <code>.tr451_vomci_nbi_message.v1.GetData get_data = 3;</code>
     */
    GetDataOrBuilder getGetDataOrBuilder();

    /**
     * <code>.tr451_vomci_nbi_message.v1.ReplaceConfig replace_config = 4;</code>
     *
     * @return Whether the replaceConfig field is set.
     */
    boolean hasReplaceConfig();

    /**
     * <code>.tr451_vomci_nbi_message.v1.ReplaceConfig replace_config = 4;</code>
     *
     * @return The replaceConfig.
     */
    ReplaceConfig getReplaceConfig();

    /**
     * <code>.tr451_vomci_nbi_message.v1.ReplaceConfig replace_config = 4;</code>
     */
    ReplaceConfigOrBuilder getReplaceConfigOrBuilder();

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfig update_config = 5;</code>
     *
     * @return Whether the updateConfig field is set.
     */
    boolean hasUpdateConfig();

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfig update_config = 5;</code>
     *
     * @return The updateConfig.
     */
    UpdateConfig getUpdateConfig();

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfig update_config = 5;</code>
     */
    UpdateConfigOrBuilder getUpdateConfigOrBuilder();

    /**
     * <code>.tr451_vomci_nbi_message.v1.RPC rpc = 6;</code>
     *
     * @return Whether the rpc field is set.
     */
    boolean hasRpc();

    /**
     * <code>.tr451_vomci_nbi_message.v1.RPC rpc = 6;</code>
     *
     * @return The rpc.
     */
    RPC getRpc();

    /**
     * <code>.tr451_vomci_nbi_message.v1.RPC rpc = 6;</code>
     */
    RPCOrBuilder getRpcOrBuilder();

    /**
     * <code>.tr451_vomci_nbi_message.v1.Action action = 7;</code>
     *
     * @return Whether the action field is set.
     */
    boolean hasAction();

    /**
     * <code>.tr451_vomci_nbi_message.v1.Action action = 7;</code>
     *
     * @return The action.
     */
    Action getAction();

    /**
     * <code>.tr451_vomci_nbi_message.v1.Action action = 7;</code>
     */
    ActionOrBuilder getActionOrBuilder();

    public Request.ReqTypeCase getReqTypeCase();
}
