// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tr451_vomci_nbi_message.proto

package org.broadband_forum.obbaa.dhcp.message.gpb.message;

/**
 * Protobuf type {@code tr451_vomci_nbi_message.v1.UpdateConfig}
 */
public final class UpdateConfig extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:tr451_vomci_nbi_message.v1.UpdateConfig)
        UpdateConfigOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use UpdateConfig.newBuilder() to construct.
    private UpdateConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private UpdateConfig() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
        return new UpdateConfig();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private UpdateConfig(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        UpdateConfigInstance.Builder subBuilder = null;
                        if (reqTypeCase_ == 1) {
                            subBuilder = ((UpdateConfigInstance) reqType_).toBuilder();
                        }
                        reqType_ =
                                input.readMessage(UpdateConfigInstance.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom((UpdateConfigInstance) reqType_);
                            reqType_ = subBuilder.buildPartial();
                        }
                        reqTypeCase_ = 1;
                        break;
                    }
                    case 18: {
                        UpdateConfigReplica.Builder subBuilder = null;
                        if (reqTypeCase_ == 2) {
                            subBuilder = ((UpdateConfigReplica) reqType_).toBuilder();
                        }
                        reqType_ =
                                input.readMessage(UpdateConfigReplica.parser(), extensionRegistry);
                        if (subBuilder != null) {
                            subBuilder.mergeFrom((UpdateConfigReplica) reqType_);
                            reqType_ = subBuilder.buildPartial();
                        }
                        reqTypeCase_ = 2;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_UpdateConfig_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_UpdateConfig_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        UpdateConfig.class, Builder.class);
    }

    private int reqTypeCase_ = 0;
    private Object reqType_;

    public enum ReqTypeCase
            implements com.google.protobuf.Internal.EnumLite,
            InternalOneOfEnum {
        UPDATE_CONFIG_INST(1),
        UPDATE_CONFIG_REPLICA(2),
        REQTYPE_NOT_SET(0);
        private final int value;

        private ReqTypeCase(int value) {
            this.value = value;
        }

        /**
         * @param value The number of the enum to look for.
         * @return The enum associated with the given number.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static ReqTypeCase valueOf(int value) {
            return forNumber(value);
        }

        public static ReqTypeCase forNumber(int value) {
            switch (value) {
                case 1:
                    return UPDATE_CONFIG_INST;
                case 2:
                    return UPDATE_CONFIG_REPLICA;
                case 0:
                    return REQTYPE_NOT_SET;
                default:
                    return null;
            }
        }

        public int getNumber() {
            return this.value;
        }
    }

    ;

    public ReqTypeCase
    getReqTypeCase() {
        return ReqTypeCase.forNumber(
                reqTypeCase_);
    }

    public static final int UPDATE_CONFIG_INST_FIELD_NUMBER = 1;

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfigInstance update_config_inst = 1;</code>
     *
     * @return Whether the updateConfigInst field is set.
     */
    @Override
    public boolean hasUpdateConfigInst() {
        return reqTypeCase_ == 1;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfigInstance update_config_inst = 1;</code>
     *
     * @return The updateConfigInst.
     */
    @Override
    public UpdateConfigInstance getUpdateConfigInst() {
        if (reqTypeCase_ == 1) {
            return (UpdateConfigInstance) reqType_;
        }
        return UpdateConfigInstance.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfigInstance update_config_inst = 1;</code>
     */
    @Override
    public UpdateConfigInstanceOrBuilder getUpdateConfigInstOrBuilder() {
        if (reqTypeCase_ == 1) {
            return (UpdateConfigInstance) reqType_;
        }
        return UpdateConfigInstance.getDefaultInstance();
    }

    public static final int UPDATE_CONFIG_REPLICA_FIELD_NUMBER = 2;

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfigReplica update_config_replica = 2;</code>
     *
     * @return Whether the updateConfigReplica field is set.
     */
    @Override
    public boolean hasUpdateConfigReplica() {
        return reqTypeCase_ == 2;
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfigReplica update_config_replica = 2;</code>
     *
     * @return The updateConfigReplica.
     */
    @Override
    public UpdateConfigReplica getUpdateConfigReplica() {
        if (reqTypeCase_ == 2) {
            return (UpdateConfigReplica) reqType_;
        }
        return UpdateConfigReplica.getDefaultInstance();
    }

    /**
     * <code>.tr451_vomci_nbi_message.v1.UpdateConfigReplica update_config_replica = 2;</code>
     */
    @Override
    public UpdateConfigReplicaOrBuilder getUpdateConfigReplicaOrBuilder() {
        if (reqTypeCase_ == 2) {
            return (UpdateConfigReplica) reqType_;
        }
        return UpdateConfigReplica.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (reqTypeCase_ == 1) {
            output.writeMessage(1, (UpdateConfigInstance) reqType_);
        }
        if (reqTypeCase_ == 2) {
            output.writeMessage(2, (UpdateConfigReplica) reqType_);
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (reqTypeCase_ == 1) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(1, (UpdateConfigInstance) reqType_);
        }
        if (reqTypeCase_ == 2) {
            size += com.google.protobuf.CodedOutputStream
                    .computeMessageSize(2, (UpdateConfigReplica) reqType_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof UpdateConfig)) {
            return super.equals(obj);
        }
        UpdateConfig other = (UpdateConfig) obj;

        if (!getReqTypeCase().equals(other.getReqTypeCase())) return false;
        switch (reqTypeCase_) {
            case 1:
                if (!getUpdateConfigInst()
                        .equals(other.getUpdateConfigInst())) return false;
                break;
            case 2:
                if (!getUpdateConfigReplica()
                        .equals(other.getUpdateConfigReplica())) return false;
                break;
            case 0:
            default:
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        switch (reqTypeCase_) {
            case 1:
                hash = (37 * hash) + UPDATE_CONFIG_INST_FIELD_NUMBER;
                hash = (53 * hash) + getUpdateConfigInst().hashCode();
                break;
            case 2:
                hash = (37 * hash) + UPDATE_CONFIG_REPLICA_FIELD_NUMBER;
                hash = (53 * hash) + getUpdateConfigReplica().hashCode();
                break;
            case 0:
            default:
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static UpdateConfig parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static UpdateConfig parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static UpdateConfig parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static UpdateConfig parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static UpdateConfig parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static UpdateConfig parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static UpdateConfig parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static UpdateConfig parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static UpdateConfig parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static UpdateConfig parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static UpdateConfig parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static UpdateConfig parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(UpdateConfig prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code tr451_vomci_nbi_message.v1.UpdateConfig}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:tr451_vomci_nbi_message.v1.UpdateConfig)
            UpdateConfigOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_UpdateConfig_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_UpdateConfig_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            UpdateConfig.class, Builder.class);
        }

        // Construct using org.broadband_forum.obbaa.dhcp.message.gpb.message.UpdateConfig.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            reqTypeCase_ = 0;
            reqType_ = null;
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Tr451VomciNbiMessage.internal_static_tr451_vomci_nbi_message_v1_UpdateConfig_descriptor;
        }

        @Override
        public UpdateConfig getDefaultInstanceForType() {
            return UpdateConfig.getDefaultInstance();
        }

        @Override
        public UpdateConfig build() {
            UpdateConfig result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public UpdateConfig buildPartial() {
            UpdateConfig result = new UpdateConfig(this);
            if (reqTypeCase_ == 1) {
                if (updateConfigInstBuilder_ == null) {
                    result.reqType_ = reqType_;
                } else {
                    result.reqType_ = updateConfigInstBuilder_.build();
                }
            }
            if (reqTypeCase_ == 2) {
                if (updateConfigReplicaBuilder_ == null) {
                    result.reqType_ = reqType_;
                } else {
                    result.reqType_ = updateConfigReplicaBuilder_.build();
                }
            }
            result.reqTypeCase_ = reqTypeCase_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof UpdateConfig) {
                return mergeFrom((UpdateConfig) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(UpdateConfig other) {
            if (other == UpdateConfig.getDefaultInstance()) return this;
            switch (other.getReqTypeCase()) {
                case UPDATE_CONFIG_INST: {
                    mergeUpdateConfigInst(other.getUpdateConfigInst());
                    break;
                }
                case UPDATE_CONFIG_REPLICA: {
                    mergeUpdateConfigReplica(other.getUpdateConfigReplica());
                    break;
                }
                case REQTYPE_NOT_SET: {
                    break;
                }
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            UpdateConfig parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (UpdateConfig) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int reqTypeCase_ = 0;
        private Object reqType_;

        public ReqTypeCase
        getReqTypeCase() {
            return ReqTypeCase.forNumber(
                    reqTypeCase_);
        }

        public Builder clearReqType() {
            reqTypeCase_ = 0;
            reqType_ = null;
            onChanged();
            return this;
        }


        private com.google.protobuf.SingleFieldBuilderV3<
                UpdateConfigInstance, UpdateConfigInstance.Builder, UpdateConfigInstanceOrBuilder> updateConfigInstBuilder_;

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigInstance update_config_inst = 1;</code>
         *
         * @return Whether the updateConfigInst field is set.
         */
        @Override
        public boolean hasUpdateConfigInst() {
            return reqTypeCase_ == 1;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigInstance update_config_inst = 1;</code>
         *
         * @return The updateConfigInst.
         */
        @Override
        public UpdateConfigInstance getUpdateConfigInst() {
            if (updateConfigInstBuilder_ == null) {
                if (reqTypeCase_ == 1) {
                    return (UpdateConfigInstance) reqType_;
                }
                return UpdateConfigInstance.getDefaultInstance();
            } else {
                if (reqTypeCase_ == 1) {
                    return updateConfigInstBuilder_.getMessage();
                }
                return UpdateConfigInstance.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigInstance update_config_inst = 1;</code>
         */
        public Builder setUpdateConfigInst(UpdateConfigInstance value) {
            if (updateConfigInstBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                reqType_ = value;
                onChanged();
            } else {
                updateConfigInstBuilder_.setMessage(value);
            }
            reqTypeCase_ = 1;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigInstance update_config_inst = 1;</code>
         */
        public Builder setUpdateConfigInst(
                UpdateConfigInstance.Builder builderForValue) {
            if (updateConfigInstBuilder_ == null) {
                reqType_ = builderForValue.build();
                onChanged();
            } else {
                updateConfigInstBuilder_.setMessage(builderForValue.build());
            }
            reqTypeCase_ = 1;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigInstance update_config_inst = 1;</code>
         */
        public Builder mergeUpdateConfigInst(UpdateConfigInstance value) {
            if (updateConfigInstBuilder_ == null) {
                if (reqTypeCase_ == 1 &&
                        reqType_ != UpdateConfigInstance.getDefaultInstance()) {
                    reqType_ = UpdateConfigInstance.newBuilder((UpdateConfigInstance) reqType_)
                            .mergeFrom(value).buildPartial();
                } else {
                    reqType_ = value;
                }
                onChanged();
            } else {
                if (reqTypeCase_ == 1) {
                    updateConfigInstBuilder_.mergeFrom(value);
                }
                updateConfigInstBuilder_.setMessage(value);
            }
            reqTypeCase_ = 1;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigInstance update_config_inst = 1;</code>
         */
        public Builder clearUpdateConfigInst() {
            if (updateConfigInstBuilder_ == null) {
                if (reqTypeCase_ == 1) {
                    reqTypeCase_ = 0;
                    reqType_ = null;
                    onChanged();
                }
            } else {
                if (reqTypeCase_ == 1) {
                    reqTypeCase_ = 0;
                    reqType_ = null;
                }
                updateConfigInstBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigInstance update_config_inst = 1;</code>
         */
        public UpdateConfigInstance.Builder getUpdateConfigInstBuilder() {
            return getUpdateConfigInstFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigInstance update_config_inst = 1;</code>
         */
        @Override
        public UpdateConfigInstanceOrBuilder getUpdateConfigInstOrBuilder() {
            if ((reqTypeCase_ == 1) && (updateConfigInstBuilder_ != null)) {
                return updateConfigInstBuilder_.getMessageOrBuilder();
            } else {
                if (reqTypeCase_ == 1) {
                    return (UpdateConfigInstance) reqType_;
                }
                return UpdateConfigInstance.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigInstance update_config_inst = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                UpdateConfigInstance, UpdateConfigInstance.Builder, UpdateConfigInstanceOrBuilder>
        getUpdateConfigInstFieldBuilder() {
            if (updateConfigInstBuilder_ == null) {
                if (!(reqTypeCase_ == 1)) {
                    reqType_ = UpdateConfigInstance.getDefaultInstance();
                }
                updateConfigInstBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        UpdateConfigInstance, UpdateConfigInstance.Builder, UpdateConfigInstanceOrBuilder>(
                        (UpdateConfigInstance) reqType_,
                        getParentForChildren(),
                        isClean());
                reqType_ = null;
            }
            reqTypeCase_ = 1;
            onChanged();
            ;
            return updateConfigInstBuilder_;
        }

        private com.google.protobuf.SingleFieldBuilderV3<
                UpdateConfigReplica, UpdateConfigReplica.Builder, UpdateConfigReplicaOrBuilder> updateConfigReplicaBuilder_;

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigReplica update_config_replica = 2;</code>
         *
         * @return Whether the updateConfigReplica field is set.
         */
        @Override
        public boolean hasUpdateConfigReplica() {
            return reqTypeCase_ == 2;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigReplica update_config_replica = 2;</code>
         *
         * @return The updateConfigReplica.
         */
        @Override
        public UpdateConfigReplica getUpdateConfigReplica() {
            if (updateConfigReplicaBuilder_ == null) {
                if (reqTypeCase_ == 2) {
                    return (UpdateConfigReplica) reqType_;
                }
                return UpdateConfigReplica.getDefaultInstance();
            } else {
                if (reqTypeCase_ == 2) {
                    return updateConfigReplicaBuilder_.getMessage();
                }
                return UpdateConfigReplica.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigReplica update_config_replica = 2;</code>
         */
        public Builder setUpdateConfigReplica(UpdateConfigReplica value) {
            if (updateConfigReplicaBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                reqType_ = value;
                onChanged();
            } else {
                updateConfigReplicaBuilder_.setMessage(value);
            }
            reqTypeCase_ = 2;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigReplica update_config_replica = 2;</code>
         */
        public Builder setUpdateConfigReplica(
                UpdateConfigReplica.Builder builderForValue) {
            if (updateConfigReplicaBuilder_ == null) {
                reqType_ = builderForValue.build();
                onChanged();
            } else {
                updateConfigReplicaBuilder_.setMessage(builderForValue.build());
            }
            reqTypeCase_ = 2;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigReplica update_config_replica = 2;</code>
         */
        public Builder mergeUpdateConfigReplica(UpdateConfigReplica value) {
            if (updateConfigReplicaBuilder_ == null) {
                if (reqTypeCase_ == 2 &&
                        reqType_ != UpdateConfigReplica.getDefaultInstance()) {
                    reqType_ = UpdateConfigReplica.newBuilder((UpdateConfigReplica) reqType_)
                            .mergeFrom(value).buildPartial();
                } else {
                    reqType_ = value;
                }
                onChanged();
            } else {
                if (reqTypeCase_ == 2) {
                    updateConfigReplicaBuilder_.mergeFrom(value);
                }
                updateConfigReplicaBuilder_.setMessage(value);
            }
            reqTypeCase_ = 2;
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigReplica update_config_replica = 2;</code>
         */
        public Builder clearUpdateConfigReplica() {
            if (updateConfigReplicaBuilder_ == null) {
                if (reqTypeCase_ == 2) {
                    reqTypeCase_ = 0;
                    reqType_ = null;
                    onChanged();
                }
            } else {
                if (reqTypeCase_ == 2) {
                    reqTypeCase_ = 0;
                    reqType_ = null;
                }
                updateConfigReplicaBuilder_.clear();
            }
            return this;
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigReplica update_config_replica = 2;</code>
         */
        public UpdateConfigReplica.Builder getUpdateConfigReplicaBuilder() {
            return getUpdateConfigReplicaFieldBuilder().getBuilder();
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigReplica update_config_replica = 2;</code>
         */
        @Override
        public UpdateConfigReplicaOrBuilder getUpdateConfigReplicaOrBuilder() {
            if ((reqTypeCase_ == 2) && (updateConfigReplicaBuilder_ != null)) {
                return updateConfigReplicaBuilder_.getMessageOrBuilder();
            } else {
                if (reqTypeCase_ == 2) {
                    return (UpdateConfigReplica) reqType_;
                }
                return UpdateConfigReplica.getDefaultInstance();
            }
        }

        /**
         * <code>.tr451_vomci_nbi_message.v1.UpdateConfigReplica update_config_replica = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<
                UpdateConfigReplica, UpdateConfigReplica.Builder, UpdateConfigReplicaOrBuilder>
        getUpdateConfigReplicaFieldBuilder() {
            if (updateConfigReplicaBuilder_ == null) {
                if (!(reqTypeCase_ == 2)) {
                    reqType_ = UpdateConfigReplica.getDefaultInstance();
                }
                updateConfigReplicaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                        UpdateConfigReplica, UpdateConfigReplica.Builder, UpdateConfigReplicaOrBuilder>(
                        (UpdateConfigReplica) reqType_,
                        getParentForChildren(),
                        isClean());
                reqType_ = null;
            }
            reqTypeCase_ = 2;
            onChanged();
            ;
            return updateConfigReplicaBuilder_;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:tr451_vomci_nbi_message.v1.UpdateConfig)
    }

    // @@protoc_insertion_point(class_scope:tr451_vomci_nbi_message.v1.UpdateConfig)
    private static final UpdateConfig DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new UpdateConfig();
    }

    public static UpdateConfig getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpdateConfig>
            PARSER = new com.google.protobuf.AbstractParser<UpdateConfig>() {
        @Override
        public UpdateConfig parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new UpdateConfig(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<UpdateConfig> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UpdateConfig> getParserForType() {
        return PARSER;
    }

    @Override
    public UpdateConfig getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

